/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import jhi.seedstore.database.codegen.enums.AttributesDatatype;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Attributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer            id;
    private String             name;
    private AttributesDatatype datatype;
    private Timestamp          createdOn;
    private Timestamp          updatedOn;

    public Attributes() {}

    public Attributes(Attributes value) {
        this.id = value.id;
        this.name = value.name;
        this.datatype = value.datatype;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Attributes(
        Integer            id,
        String             name,
        AttributesDatatype datatype,
        Timestamp          createdOn,
        Timestamp          updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.datatype = datatype;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Attributes (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(datatype);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
