/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContainerAttributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   attributeId;
    private Integer   containerId;
    private String    attributeValue;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ContainerAttributes() {}

    public ContainerAttributes(ContainerAttributes value) {
        this.attributeId = value.attributeId;
        this.containerId = value.containerId;
        this.attributeValue = value.attributeValue;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ContainerAttributes(
        Integer   attributeId,
        Integer   containerId,
        String    attributeValue,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.attributeId = attributeId;
        this.containerId = containerId;
        this.attributeValue = attributeValue;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContainerAttributes (");

        sb.append(attributeId);
        sb.append(", ").append(containerId);
        sb.append(", ").append(attributeValue);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
