/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Map;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContainerAttributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer containerId;
    private Map<Integer,String> attributeValues;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ContainerAttributes() {}

    public ContainerAttributes(ContainerAttributes value) {
        this.id = value.id;
        this.containerId = value.containerId;
        this.attributeValues = value.attributeValues;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ContainerAttributes(
        Integer id,
        Integer containerId,
        Map<Integer,String> attributeValues,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.containerId = containerId;
        this.attributeValues = attributeValues;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ContainerAttributes other = (ContainerAttributes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.containerId == null) {
            if (other.containerId != null)
                return false;
        }
        else if (!this.containerId.equals(other.containerId))
            return false;
        if (this.attributeValues == null) {
            if (other.attributeValues != null)
                return false;
        }
        else if (!this.attributeValues.equals(other.attributeValues))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.containerId == null) ? 0 : this.containerId.hashCode());
        result = prime * result + ((this.attributeValues == null) ? 0 : this.attributeValues.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContainerAttributes (");

        sb.append(id);
        sb.append(", ").append(containerId);
        sb.append(", ").append(attributeValues);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
