/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Containers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    barcode;
    private String    description;
    private Integer   containerTypeId;
    private Integer   parentContainerId;
    private Boolean   isActive;
    private Integer   trialId;
    private Integer   projectId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Containers() {}

    public Containers(Containers value) {
        this.id = value.id;
        this.barcode = value.barcode;
        this.description = value.description;
        this.containerTypeId = value.containerTypeId;
        this.parentContainerId = value.parentContainerId;
        this.isActive = value.isActive;
        this.trialId = value.trialId;
        this.projectId = value.projectId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Containers(
        Integer   id,
        String    barcode,
        String    description,
        Integer   containerTypeId,
        Integer   parentContainerId,
        Boolean   isActive,
        Integer   trialId,
        Integer   projectId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.barcode = barcode;
        this.description = description;
        this.containerTypeId = containerTypeId;
        this.parentContainerId = parentContainerId;
        this.isActive = isActive;
        this.trialId = trialId;
        this.projectId = projectId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Containers (");

        sb.append(id);
        sb.append(", ").append(barcode);
        sb.append(", ").append(description);
        sb.append(", ").append(containerTypeId);
        sb.append(", ").append(parentContainerId);
        sb.append(", ").append(isActive);
        sb.append(", ").append(trialId);
        sb.append(", ").append(projectId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
