/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Projects implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    name;
    private String    description;
    private Integer   userId;
    private Date      startDate;
    private Date      endDate;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Projects() {}

    public Projects(Projects value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.userId = value.userId;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Projects(
        Integer   id,
        String    name,
        String    description,
        Integer   userId,
        Date      startDate,
        Date      endDate,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.userId = userId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Projects (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(userId);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
