/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransferLogs implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer transferEventId;
    private Integer containerId;
    private Integer sourceId;
    private Integer targetId;
    private Integer userId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public TransferLogs() {}

    public TransferLogs(TransferLogs value) {
        this.transferEventId = value.transferEventId;
        this.containerId = value.containerId;
        this.sourceId = value.sourceId;
        this.targetId = value.targetId;
        this.userId = value.userId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public TransferLogs(
        Integer transferEventId,
        Integer containerId,
        Integer sourceId,
        Integer targetId,
        Integer userId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.transferEventId = transferEventId;
        this.containerId = containerId;
        this.sourceId = sourceId;
        this.targetId = targetId;
        this.userId = userId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TransferLogs other = (TransferLogs) obj;
        if (this.transferEventId == null) {
            if (other.transferEventId != null)
                return false;
        }
        else if (!this.transferEventId.equals(other.transferEventId))
            return false;
        if (this.containerId == null) {
            if (other.containerId != null)
                return false;
        }
        else if (!this.containerId.equals(other.containerId))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        if (this.targetId == null) {
            if (other.targetId != null)
                return false;
        }
        else if (!this.targetId.equals(other.targetId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.transferEventId == null) ? 0 : this.transferEventId.hashCode());
        result = prime * result + ((this.containerId == null) ? 0 : this.containerId.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.targetId == null) ? 0 : this.targetId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransferLogs (");

        sb.append(transferEventId);
        sb.append(", ").append(containerId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(targetId);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
