/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import lombok.*;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.sql.Timestamp;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferLogs implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   containerId;
    private Integer   sourceId;
    private Integer   targetId;
    private Integer   userId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public TransferLogs() {}

    public TransferLogs(TransferLogs value) {
        this.id = value.id;
        this.containerId = value.containerId;
        this.sourceId = value.sourceId;
        this.targetId = value.targetId;
        this.userId = value.userId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public TransferLogs(
        Integer   id,
        Integer   containerId,
        Integer   sourceId,
        Integer   targetId,
        Integer   userId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.containerId = containerId;
        this.sourceId = sourceId;
        this.targetId = targetId;
        this.userId = userId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransferLogs (");

        sb.append(id);
        sb.append(", ").append(containerId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(targetId);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
