/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import lombok.*;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.sql.*;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trials implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    name;
    private String    description;
    private Integer   projectId;
    private Short     rowCount;
    private Short     columnCount;
    private byte[]    shapefile;
    private Integer   userId;
    private Date      startDate;
    private Date      endDate;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Trials() {}

    public Trials(Trials value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.projectId = value.projectId;
        this.rowCount = value.rowCount;
        this.columnCount = value.columnCount;
        this.shapefile = value.shapefile;
        this.userId = value.userId;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Trials(
        Integer   id,
        String    name,
        String    description,
        Integer   projectId,
        Short     rowCount,
        Short     columnCount,
        byte[]    shapefile,
        Integer   userId,
        Date      startDate,
        Date      endDate,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.projectId = projectId;
        this.rowCount = rowCount;
        this.columnCount = columnCount;
        this.shapefile = shapefile;
        this.userId = userId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trials (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(projectId);
        sb.append(", ").append(rowCount);
        sb.append(", ").append(columnCount);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(userId);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
