/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import org.jooq.JSON;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTransfers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer transferEventId;
    private Integer containerId;
    private String containerBarcode;
    private JSON containerAttributes;
    private Integer sourceId;
    private String sourceBarcode;
    private JSON sourceAttributes;
    private Integer targetId;
    private String targetBarcode;
    private JSON targetAttributes;
    private Integer userId;
    private String userName;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ViewTableTransfers() {}

    public ViewTableTransfers(ViewTableTransfers value) {
        this.transferEventId = value.transferEventId;
        this.containerId = value.containerId;
        this.containerBarcode = value.containerBarcode;
        this.containerAttributes = value.containerAttributes;
        this.sourceId = value.sourceId;
        this.sourceBarcode = value.sourceBarcode;
        this.sourceAttributes = value.sourceAttributes;
        this.targetId = value.targetId;
        this.targetBarcode = value.targetBarcode;
        this.targetAttributes = value.targetAttributes;
        this.userId = value.userId;
        this.userName = value.userName;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ViewTableTransfers(
        Integer transferEventId,
        Integer containerId,
        String containerBarcode,
        JSON containerAttributes,
        Integer sourceId,
        String sourceBarcode,
        JSON sourceAttributes,
        Integer targetId,
        String targetBarcode,
        JSON targetAttributes,
        Integer userId,
        String userName,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.transferEventId = transferEventId;
        this.containerId = containerId;
        this.containerBarcode = containerBarcode;
        this.containerAttributes = containerAttributes;
        this.sourceId = sourceId;
        this.sourceBarcode = sourceBarcode;
        this.sourceAttributes = sourceAttributes;
        this.targetId = targetId;
        this.targetBarcode = targetBarcode;
        this.targetAttributes = targetAttributes;
        this.userId = userId;
        this.userName = userName;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ViewTableTransfers other = (ViewTableTransfers) obj;
        if (this.transferEventId == null) {
            if (other.transferEventId != null)
                return false;
        }
        else if (!this.transferEventId.equals(other.transferEventId))
            return false;
        if (this.containerId == null) {
            if (other.containerId != null)
                return false;
        }
        else if (!this.containerId.equals(other.containerId))
            return false;
        if (this.containerBarcode == null) {
            if (other.containerBarcode != null)
                return false;
        }
        else if (!this.containerBarcode.equals(other.containerBarcode))
            return false;
        if (this.containerAttributes == null) {
            if (other.containerAttributes != null)
                return false;
        }
        else if (!this.containerAttributes.equals(other.containerAttributes))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        if (this.sourceBarcode == null) {
            if (other.sourceBarcode != null)
                return false;
        }
        else if (!this.sourceBarcode.equals(other.sourceBarcode))
            return false;
        if (this.sourceAttributes == null) {
            if (other.sourceAttributes != null)
                return false;
        }
        else if (!this.sourceAttributes.equals(other.sourceAttributes))
            return false;
        if (this.targetId == null) {
            if (other.targetId != null)
                return false;
        }
        else if (!this.targetId.equals(other.targetId))
            return false;
        if (this.targetBarcode == null) {
            if (other.targetBarcode != null)
                return false;
        }
        else if (!this.targetBarcode.equals(other.targetBarcode))
            return false;
        if (this.targetAttributes == null) {
            if (other.targetAttributes != null)
                return false;
        }
        else if (!this.targetAttributes.equals(other.targetAttributes))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!this.userName.equals(other.userName))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.transferEventId == null) ? 0 : this.transferEventId.hashCode());
        result = prime * result + ((this.containerId == null) ? 0 : this.containerId.hashCode());
        result = prime * result + ((this.containerBarcode == null) ? 0 : this.containerBarcode.hashCode());
        result = prime * result + ((this.containerAttributes == null) ? 0 : this.containerAttributes.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.sourceBarcode == null) ? 0 : this.sourceBarcode.hashCode());
        result = prime * result + ((this.sourceAttributes == null) ? 0 : this.sourceAttributes.hashCode());
        result = prime * result + ((this.targetId == null) ? 0 : this.targetId.hashCode());
        result = prime * result + ((this.targetBarcode == null) ? 0 : this.targetBarcode.hashCode());
        result = prime * result + ((this.targetAttributes == null) ? 0 : this.targetAttributes.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableTransfers (");

        sb.append(transferEventId);
        sb.append(", ").append(containerId);
        sb.append(", ").append(containerBarcode);
        sb.append(", ").append(containerAttributes);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(sourceBarcode);
        sb.append(", ").append(sourceAttributes);
        sb.append(", ").append(targetId);
        sb.append(", ").append(targetBarcode);
        sb.append(", ").append(targetAttributes);
        sb.append(", ").append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
