/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTransferEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer eventId;
    private Timestamp timestamp;
    private Integer sourceId;
    private String sourceBarcode;
    private Integer sourceTypeId;
    private Integer targetId;
    private String targetBarcode;
    private Integer targetTypeId;
    private Integer userId;
    private String userName;
    private Long containerCount;
    private Integer[] containerIds;

    public ViewTableTransferEvents() {}

    public ViewTableTransferEvents(ViewTableTransferEvents value) {
        this.eventId = value.eventId;
        this.timestamp = value.timestamp;
        this.sourceId = value.sourceId;
        this.sourceBarcode = value.sourceBarcode;
        this.sourceTypeId = value.sourceTypeId;
        this.targetId = value.targetId;
        this.targetBarcode = value.targetBarcode;
        this.targetTypeId = value.targetTypeId;
        this.userId = value.userId;
        this.userName = value.userName;
        this.containerCount = value.containerCount;
        this.containerIds = value.containerIds;
    }

    public ViewTableTransferEvents(
        Integer eventId,
        Timestamp timestamp,
        Integer sourceId,
        String sourceBarcode,
        Integer sourceTypeId,
        Integer targetId,
        String targetBarcode,
        Integer targetTypeId,
        Integer userId,
        String userName,
        Long containerCount,
        Integer[] containerIds
    ) {
        this.eventId = eventId;
        this.timestamp = timestamp;
        this.sourceId = sourceId;
        this.sourceBarcode = sourceBarcode;
        this.sourceTypeId = sourceTypeId;
        this.targetId = targetId;
        this.targetBarcode = targetBarcode;
        this.targetTypeId = targetTypeId;
        this.userId = userId;
        this.userName = userName;
        this.containerCount = containerCount;
        this.containerIds = containerIds;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ViewTableTransferEvents other = (ViewTableTransferEvents) obj;
        if (this.eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!this.eventId.equals(other.eventId))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        if (this.sourceBarcode == null) {
            if (other.sourceBarcode != null)
                return false;
        }
        else if (!this.sourceBarcode.equals(other.sourceBarcode))
            return false;
        if (this.sourceTypeId == null) {
            if (other.sourceTypeId != null)
                return false;
        }
        else if (!this.sourceTypeId.equals(other.sourceTypeId))
            return false;
        if (this.targetId == null) {
            if (other.targetId != null)
                return false;
        }
        else if (!this.targetId.equals(other.targetId))
            return false;
        if (this.targetBarcode == null) {
            if (other.targetBarcode != null)
                return false;
        }
        else if (!this.targetBarcode.equals(other.targetBarcode))
            return false;
        if (this.targetTypeId == null) {
            if (other.targetTypeId != null)
                return false;
        }
        else if (!this.targetTypeId.equals(other.targetTypeId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!this.userName.equals(other.userName))
            return false;
        if (this.containerCount == null) {
            if (other.containerCount != null)
                return false;
        }
        else if (!this.containerCount.equals(other.containerCount))
            return false;
        if (this.containerIds == null) {
            if (other.containerIds != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.containerIds, other.containerIds))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.sourceBarcode == null) ? 0 : this.sourceBarcode.hashCode());
        result = prime * result + ((this.sourceTypeId == null) ? 0 : this.sourceTypeId.hashCode());
        result = prime * result + ((this.targetId == null) ? 0 : this.targetId.hashCode());
        result = prime * result + ((this.targetBarcode == null) ? 0 : this.targetBarcode.hashCode());
        result = prime * result + ((this.targetTypeId == null) ? 0 : this.targetTypeId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.containerCount == null) ? 0 : this.containerCount.hashCode());
        result = prime * result + ((this.containerIds == null) ? 0 : Arrays.deepHashCode(this.containerIds));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableTransferEvents (");

        sb.append(eventId);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(sourceBarcode);
        sb.append(", ").append(sourceTypeId);
        sb.append(", ").append(targetId);
        sb.append(", ").append(targetBarcode);
        sb.append(", ").append(targetTypeId);
        sb.append(", ").append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(containerCount);
        sb.append(", ").append(Arrays.deepToString(containerIds));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
