/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableTransferEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    private String    eventId;
    private Timestamp timestamp;
    private Integer   sourceId;
    private String    sourceBarcode;
    private String    sourceType;
    private Integer   targetId;
    private String    targetBarcode;
    private String    targetType;
    private Integer   userId;
    private String    userName;
    private Long      containerCount;
    private Integer[] containerIds;

    public ViewTableTransferEvents() {}

    public ViewTableTransferEvents(ViewTableTransferEvents value) {
        this.eventId = value.eventId;
        this.timestamp = value.timestamp;
        this.sourceId = value.sourceId;
        this.sourceBarcode = value.sourceBarcode;
        this.sourceType = value.sourceType;
        this.targetId = value.targetId;
        this.targetBarcode = value.targetBarcode;
        this.targetType = value.targetType;
        this.userId = value.userId;
        this.userName = value.userName;
        this.containerCount = value.containerCount;
        this.containerIds = value.containerIds;
    }

    public ViewTableTransferEvents(
        String    eventId,
        Timestamp timestamp,
        Integer   sourceId,
        String    sourceBarcode,
        String    sourceType,
        Integer   targetId,
        String    targetBarcode,
        String    targetType,
        Integer   userId,
        String    userName,
        Long      containerCount,
        Integer[] containerIds
    ) {
        this.eventId = eventId;
        this.timestamp = timestamp;
        this.sourceId = sourceId;
        this.sourceBarcode = sourceBarcode;
        this.sourceType = sourceType;
        this.targetId = targetId;
        this.targetBarcode = targetBarcode;
        this.targetType = targetType;
        this.userId = userId;
        this.userName = userName;
        this.containerCount = containerCount;
        this.containerIds = containerIds;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableTransferEvents (");

        sb.append(eventId);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(sourceBarcode);
        sb.append(", ").append(sourceType);
        sb.append(", ").append(targetId);
        sb.append(", ").append(targetBarcode);
        sb.append(", ").append(targetType);
        sb.append(", ").append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(containerCount);
        sb.append(", ").append(Arrays.toString(containerIds));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
