/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Map;

import jhi.seedstore.database.codegen.enums.ViewTableUsersUserType;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String emailAddress;
    private ViewTableUsersUserType userType;
    private Timestamp lastLogin;
    private Timestamp createdOn;
    private Map<String,Integer> stats;

    public ViewTableUsers() {}

    public ViewTableUsers(ViewTableUsers value) {
        this.id = value.id;
        this.name = value.name;
        this.emailAddress = value.emailAddress;
        this.userType = value.userType;
        this.lastLogin = value.lastLogin;
        this.createdOn = value.createdOn;
        this.stats = value.stats;
    }

    public ViewTableUsers(
        Integer id,
        String name,
        String emailAddress,
        ViewTableUsersUserType userType,
        Timestamp lastLogin,
        Timestamp createdOn,
        Map<String,Integer> stats
    ) {
        this.id = id;
        this.name = name;
        this.emailAddress = emailAddress;
        this.userType = userType;
        this.lastLogin = lastLogin;
        this.createdOn = createdOn;
        this.stats = stats;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ViewTableUsers other = (ViewTableUsers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.emailAddress == null) {
            if (other.emailAddress != null)
                return false;
        }
        else if (!this.emailAddress.equals(other.emailAddress))
            return false;
        if (this.userType == null) {
            if (other.userType != null)
                return false;
        }
        else if (!this.userType.equals(other.userType))
            return false;
        if (this.lastLogin == null) {
            if (other.lastLogin != null)
                return false;
        }
        else if (!this.lastLogin.equals(other.lastLogin))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.stats == null) {
            if (other.stats != null)
                return false;
        }
        else if (!this.stats.equals(other.stats))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.emailAddress == null) ? 0 : this.emailAddress.hashCode());
        result = prime * result + ((this.userType == null) ? 0 : this.userType.hashCode());
        result = prime * result + ((this.lastLogin == null) ? 0 : this.lastLogin.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.stats == null) ? 0 : this.stats.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableUsers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(userType);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(stats);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
