/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Map;

import jhi.seedstore.database.codegen.enums.ViewTableUsersUserType;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer                id;
    private String                 name;
    private String                 emailAddress;
    private ViewTableUsersUserType userType;
    private Timestamp              lastLogin;
    private Timestamp              createdOn;
    private Map<String,Integer>    stats;

    public ViewTableUsers() {}

    public ViewTableUsers(ViewTableUsers value) {
        this.id = value.id;
        this.name = value.name;
        this.emailAddress = value.emailAddress;
        this.userType = value.userType;
        this.lastLogin = value.lastLogin;
        this.createdOn = value.createdOn;
        this.stats = value.stats;
    }

    public ViewTableUsers(
        Integer                id,
        String                 name,
        String                 emailAddress,
        ViewTableUsersUserType userType,
        Timestamp              lastLogin,
        Timestamp              createdOn,
        Map<String,Integer>    stats
    ) {
        this.id = id;
        this.name = name;
        this.emailAddress = emailAddress;
        this.userType = userType;
        this.lastLogin = lastLogin;
        this.createdOn = createdOn;
        this.stats = stats;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableUsers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(userType);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(stats);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
