DROP VIEW IF EXISTS `view_table_containers`;
CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW `view_table_containers` AS SELECT `c`.`id` AS `container_id`, `c`.`barcode` AS `container_barcode`, `ct`.`id` AS `container_type_id`, `cp`.`id` AS `parent_id`, `cp`.`barcode` AS `parent_barcode`, `ctp`.`id` AS `parent_container_type_id`, `c`.`is_active` AS `container_is_active`, `trials`.`id` AS `trial_id`, `trials`.`name` AS `trial_name`, `trials`.`description` AS `trial_description`, `projects`.`id` AS `project_id`, `projects`.`name` AS `project_name`, `projects`.`description` AS `project_description`,( SELECT JSON_ARRAYAGG(json_obj) from ( select json_object( 'date', cast( `container_attributes`.`created_on` AS DATE ), 'attributeValues', `container_attributes`.`attribute_values` ) as json_obj FROM `container_attributes` WHERE ( `container_attributes`.`container_id` = `c`.`id` ) order by `container_attributes`.`created_on` desc limit 1 ) x) AS `container_attributes`,( SELECT count( 1 ) FROM `containers` `sc` WHERE ( `sc`.`parent_container_id` = `c`.`id` )) AS `sub_container_count`, `c`.`created_on` AS `created_on` FROM `containers` `c` LEFT JOIN `containers` `cp` ON `c`.`parent_container_id` = `cp`.`id` LEFT JOIN `container_types` `ct` ON `c`.`container_type_id` = `ct`.`id` LEFT JOIN `container_types` `ctp` ON `cp`.`container_type_id` = `ctp`.`id` LEFT JOIN `trials` ON `trials`.`id` = `c`.`trial_id` LEFT JOIN `projects` ON `projects`.`id` = `c`.`project_id`;

DROP VIEW IF EXISTS `view_table_transfers`;
CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW `view_table_transfers` AS SELECT `transfer_logs`.`transfer_event_id` AS `transfer_event_id`, `c`.`id` AS `container_id`, `c`.`barcode` AS `container_barcode`, ( SELECT JSON_ARRAYAGG( json_obj ) FROM ( SELECT json_object( 'date', cast( `container_attributes`.`created_on` AS DATE ), 'attributeValues', `container_attributes`.`attribute_values` ) AS json_obj FROM `container_attributes` WHERE ( `container_attributes`.`container_id` = `c`.`id` ) ORDER BY `container_attributes`.`created_on` DESC LIMIT 1 ) x ) AS `container_attributes`, `s`.`id` AS `source_id`, `s`.`barcode` AS `source_barcode`, ( SELECT JSON_ARRAYAGG( json_obj ) FROM ( SELECT json_object( 'date', cast( `container_attributes`.`created_on` AS DATE ), 'attributeValues', `container_attributes`.`attribute_values` ) AS json_obj FROM `container_attributes` WHERE ( `container_attributes`.`container_id` = `s`.`id` ) ORDER BY `container_attributes`.`created_on` DESC LIMIT 1 ) x ) AS `source_attributes`, `t`.`id` AS `target_id`, `t`.`barcode` AS `target_barcode`, ( SELECT JSON_ARRAYAGG( json_obj ) FROM ( SELECT json_object( 'date', cast( `container_attributes`.`created_on` AS DATE ), 'attributeValues', `container_attributes`.`attribute_values` ) AS json_obj FROM `container_attributes` WHERE ( `container_attributes`.`container_id` = `t`.`id` ) ORDER BY `container_attributes`.`created_on` DESC LIMIT 1 ) x ) AS `target_attributes`, `users`.`id` AS `user_id`, `users`.`name` AS `user_name`, `transfer_logs`.`created_on` AS `created_on`, `transfer_logs`.`updated_on` AS `updated_on` FROM `transfer_logs` LEFT JOIN `containers` `c` ON `c`.`id` = `transfer_logs`.`container_id` LEFT JOIN `containers` `s` ON `s`.`id` = `transfer_logs`.`source_id` LEFT JOIN `containers` `t` ON `t`.`id` = `transfer_logs`.`target_id` LEFT JOIN `users` ON `transfer_logs`.`user_id` = `users`.`id`;

DROP VIEW IF EXISTS `view_table_transfer_events`;
CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW `view_table_transfer_events` AS select `transfer_logs`.`transfer_event_id` AS `event_id`,max(`transfer_logs`.`created_on`) AS `timestamp`,`s`.`id` AS `source_id`,`s`.`barcode` AS `source_barcode`,`st`.`id` AS `source_type_id`,`t`.`id` AS `target_id`,`t`.`barcode` AS `target_barcode`,`tt`.`id` AS `target_type_id`,`users`.`id` AS `user_id`,`users`.`name` AS `user_name`,count(1) AS `container_count`,json_arrayagg(`transfer_logs`.`container_id`) AS `container_ids` from (((((`transfer_logs` left join `containers` `s` on((`transfer_logs`.`source_id` = `s`.`id`))) left join `containers` `t` on((`transfer_logs`.`target_id` = `t`.`id`))) left join `container_types` `st` on((`st`.`id` = `s`.`container_type_id`))) left join `container_types` `tt` on((`tt`.`id` = `t`.`container_type_id`))) left join `users` on((`users`.`id` = `transfer_logs`.`user_id`))) group by `transfer_logs`.`source_id`,`transfer_logs`.`target_id`,`transfer_logs`.`user_id`,`transfer_logs`.`transfer_event_id`;

DROP VIEW IF EXISTS `view_table_users`;
CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW `view_table_users` AS select users.id, users.name, users.email_address, users.user_type, users.last_login, users.created_on, json_objectagg(ifnull(t.yearmonth, 'null'), t.count) as stats from users left join ( select user_id, date_format(created_on, '%Y-%m') as yearmonth, count(1) as count from transfer_logs where datediff(now(), transfer_logs.created_on) <= 365 group by user_id, date_format(created_on, '%Y-%m') ) t on t.user_id = users.id group by users.id;