/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import jhi.seedstore.database.codegen.enums.AttributesDatatype;
import jhi.seedstore.database.codegen.tables.Attributes;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttributesRecord extends UpdatableRecordImpl<AttributesRecord> implements Record5<Integer, String, AttributesDatatype, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.attributes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.attributes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seedstore_db.attributes.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>seedstore_db.attributes.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>seedstore_db.attributes.datatype</code>.
     */
    public void setDatatype(AttributesDatatype value) {
        set(2, value);
    }

    /**
     * Getter for <code>seedstore_db.attributes.datatype</code>.
     */
    public AttributesDatatype getDatatype() {
        return (AttributesDatatype) get(2);
    }

    /**
     * Setter for <code>seedstore_db.attributes.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>seedstore_db.attributes.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>seedstore_db.attributes.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>seedstore_db.attributes.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, AttributesDatatype, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, AttributesDatatype, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Attributes.ATTRIBUTES.ID;
    }

    @Override
    public Field<String> field2() {
        return Attributes.ATTRIBUTES.NAME;
    }

    @Override
    public Field<AttributesDatatype> field3() {
        return Attributes.ATTRIBUTES.DATATYPE;
    }

    @Override
    public Field<Timestamp> field4() {
        return Attributes.ATTRIBUTES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field5() {
        return Attributes.ATTRIBUTES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public AttributesDatatype component3() {
        return getDatatype();
    }

    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public AttributesDatatype value3() {
        return getDatatype();
    }

    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    @Override
    public AttributesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AttributesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AttributesRecord value3(AttributesDatatype value) {
        setDatatype(value);
        return this;
    }

    @Override
    public AttributesRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public AttributesRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public AttributesRecord values(Integer value1, String value2, AttributesDatatype value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttributesRecord
     */
    public AttributesRecord() {
        super(Attributes.ATTRIBUTES);
    }

    /**
     * Create a detached, initialised AttributesRecord
     */
    public AttributesRecord(Integer id, String name, AttributesDatatype datatype, Timestamp createdOn, Timestamp updatedOn) {
        super(Attributes.ATTRIBUTES);

        setId(id);
        setName(name);
        setDatatype(datatype);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised AttributesRecord
     */
    public AttributesRecord(jhi.seedstore.database.codegen.tables.pojos.Attributes value) {
        super(Attributes.ATTRIBUTES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDatatype(value.getDatatype());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
