/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.enums.AttributesDatatype;
import jhi.seedstore.database.codegen.tables.Attributes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttributesRecord extends UpdatableRecordImpl<AttributesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.attributes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.attributes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.attributes.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.attributes.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.attributes.datatype</code>.
     */
    public void setDatatype(AttributesDatatype value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.attributes.datatype</code>.
     */
    public AttributesDatatype getDatatype() {
        return (AttributesDatatype) get(2);
    }

    /**
     * Setter for <code>stash_db.attributes.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.attributes.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>stash_db.attributes.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.attributes.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttributesRecord
     */
    public AttributesRecord() {
        super(Attributes.ATTRIBUTES);
    }

    /**
     * Create a detached, initialised AttributesRecord
     */
    public AttributesRecord(Integer id, String name, AttributesDatatype datatype, Timestamp createdOn, Timestamp updatedOn) {
        super(Attributes.ATTRIBUTES);

        setId(id);
        setName(name);
        setDatatype(datatype);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AttributesRecord
     */
    public AttributesRecord(jhi.seedstore.database.codegen.tables.pojos.Attributes value) {
        super(Attributes.ATTRIBUTES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDatatype(value.getDatatype());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
