/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;
import java.util.Map;

import jhi.seedstore.database.codegen.tables.ContainerAttributes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContainerAttributesRecord extends UpdatableRecordImpl<ContainerAttributesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.container_attributes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.container_attributes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.container_attributes.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.container_attributes.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stash_db.container_attributes.attribute_values</code>.
     */
    public void setAttributeValues(Map<Integer,String> value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.container_attributes.attribute_values</code>.
     */
    public Map<Integer,String> getAttributeValues() {
        return (Map<Integer,String>) get(2);
    }

    /**
     * Setter for <code>stash_db.container_attributes.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.container_attributes.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>stash_db.container_attributes.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.container_attributes.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainerAttributesRecord
     */
    public ContainerAttributesRecord() {
        super(ContainerAttributes.CONTAINER_ATTRIBUTES);
    }

    /**
     * Create a detached, initialised ContainerAttributesRecord
     */
    public ContainerAttributesRecord(Integer id, Integer containerId, Map<Integer,String> attributeValues, Timestamp createdOn, Timestamp updatedOn) {
        super(ContainerAttributes.CONTAINER_ATTRIBUTES);

        setId(id);
        setContainerId(containerId);
        setAttributeValues(attributeValues);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ContainerAttributesRecord
     */
    public ContainerAttributesRecord(jhi.seedstore.database.codegen.tables.pojos.ContainerAttributes value) {
        super(ContainerAttributes.CONTAINER_ATTRIBUTES);

        if (value != null) {
            setId(value.getId());
            setContainerId(value.getContainerId());
            setAttributeValues(value.getAttributeValues());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
