/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.Containers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContainersRecord extends UpdatableRecordImpl<ContainersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.containers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.containers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.containers.barcode</code>.
     */
    public void setBarcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.containers.barcode</code>.
     */
    public String getBarcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.containers.container_type_id</code>.
     */
    public void setContainerTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.containers.container_type_id</code>.
     */
    public Integer getContainerTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>stash_db.containers.parent_container_id</code>.
     */
    public void setParentContainerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.containers.parent_container_id</code>.
     */
    public Integer getParentContainerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>stash_db.containers.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.containers.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>stash_db.containers.trial_id</code>.
     */
    public void setTrialId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.containers.trial_id</code>.
     */
    public Integer getTrialId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>stash_db.containers.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.containers.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>stash_db.containers.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>stash_db.containers.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>stash_db.containers.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>stash_db.containers.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainersRecord
     */
    public ContainersRecord() {
        super(Containers.CONTAINERS);
    }

    /**
     * Create a detached, initialised ContainersRecord
     */
    public ContainersRecord(Integer id, String barcode, Integer containerTypeId, Integer parentContainerId, Boolean isActive, Integer trialId, Integer projectId, Timestamp createdOn, Timestamp updatedOn) {
        super(Containers.CONTAINERS);

        setId(id);
        setBarcode(barcode);
        setContainerTypeId(containerTypeId);
        setParentContainerId(parentContainerId);
        setIsActive(isActive);
        setTrialId(trialId);
        setProjectId(projectId);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ContainersRecord
     */
    public ContainersRecord(jhi.seedstore.database.codegen.tables.pojos.Containers value) {
        super(Containers.CONTAINERS);

        if (value != null) {
            setId(value.getId());
            setBarcode(value.getBarcode());
            setContainerTypeId(value.getContainerTypeId());
            setParentContainerId(value.getParentContainerId());
            setIsActive(value.getIsActive());
            setTrialId(value.getTrialId());
            setProjectId(value.getProjectId());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
