/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ContainerTypes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContainerTypesRecord extends UpdatableRecordImpl<ContainerTypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.container_types.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.container_types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.container_types.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.container_types.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.container_types.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.container_types.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stash_db.container_types.icon</code>.
     */
    public void setIcon(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.container_types.icon</code>.
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stash_db.container_types.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.container_types.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>stash_db.container_types.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.container_types.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainerTypesRecord
     */
    public ContainerTypesRecord() {
        super(ContainerTypes.CONTAINER_TYPES);
    }

    /**
     * Create a detached, initialised ContainerTypesRecord
     */
    public ContainerTypesRecord(Integer id, String name, String description, String icon, Timestamp createdOn, Timestamp updatedOn) {
        super(ContainerTypes.CONTAINER_TYPES);

        setId(id);
        setName(name);
        setDescription(description);
        setIcon(icon);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ContainerTypesRecord
     */
    public ContainerTypesRecord(jhi.seedstore.database.codegen.tables.pojos.ContainerTypes value) {
        super(ContainerTypes.CONTAINER_TYPES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setIcon(value.getIcon());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
