/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ContainerTypes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContainerTypesRecord extends UpdatableRecordImpl<ContainerTypesRecord> implements Record6<Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.container_types.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.container_types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seedstore_db.container_types.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>seedstore_db.container_types.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>seedstore_db.container_types.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>seedstore_db.container_types.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>seedstore_db.container_types.icon</code>.
     */
    public void setIcon(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>seedstore_db.container_types.icon</code>.
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>seedstore_db.container_types.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>seedstore_db.container_types.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>seedstore_db.container_types.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>seedstore_db.container_types.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ContainerTypes.CONTAINER_TYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return ContainerTypes.CONTAINER_TYPES.NAME;
    }

    @Override
    public Field<String> field3() {
        return ContainerTypes.CONTAINER_TYPES.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return ContainerTypes.CONTAINER_TYPES.ICON;
    }

    @Override
    public Field<Timestamp> field5() {
        return ContainerTypes.CONTAINER_TYPES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field6() {
        return ContainerTypes.CONTAINER_TYPES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getIcon();
    }

    @Override
    public Timestamp component5() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component6() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getIcon();
    }

    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value6() {
        return getUpdatedOn();
    }

    @Override
    public ContainerTypesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ContainerTypesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ContainerTypesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ContainerTypesRecord value4(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public ContainerTypesRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ContainerTypesRecord value6(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ContainerTypesRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainerTypesRecord
     */
    public ContainerTypesRecord() {
        super(ContainerTypes.CONTAINER_TYPES);
    }

    /**
     * Create a detached, initialised ContainerTypesRecord
     */
    public ContainerTypesRecord(Integer id, String name, String description, String icon, Timestamp createdOn, Timestamp updatedOn) {
        super(ContainerTypes.CONTAINER_TYPES);

        setId(id);
        setName(name);
        setDescription(description);
        setIcon(icon);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ContainerTypesRecord
     */
    public ContainerTypesRecord(jhi.seedstore.database.codegen.tables.pojos.ContainerTypes value) {
        super(ContainerTypes.CONTAINER_TYPES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setIcon(value.getIcon());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
