/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import jhi.seedstore.database.codegen.tables.ContainerAttributes;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContainerAttributesRecord extends UpdatableRecordImpl<ContainerAttributesRecord> implements Record5<Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.container_attributes.attribute_id</code>.
     */
    public void setAttributeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.container_attributes.attribute_id</code>.
     */
    public Integer getAttributeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seedstore_db.container_attributes.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>seedstore_db.container_attributes.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>seedstore_db.container_attributes.attribute_value</code>.
     */
    public void setAttributeValue(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.container_attributes.attribute_value</code>.
     */
    public String getAttributeValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>seedstore_db.container_attributes.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>seedstore_db.container_attributes.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>seedstore_db.container_attributes.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>seedstore_db.container_attributes.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ContainerAttributes.CONTAINER_ATTRIBUTES.ATTRIBUTE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ContainerAttributes.CONTAINER_ATTRIBUTES.CONTAINER_ID;
    }

    @Override
    public Field<String> field3() {
        return ContainerAttributes.CONTAINER_ATTRIBUTES.ATTRIBUTE_VALUE;
    }

    @Override
    public Field<Timestamp> field4() {
        return ContainerAttributes.CONTAINER_ATTRIBUTES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field5() {
        return ContainerAttributes.CONTAINER_ATTRIBUTES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getAttributeId();
    }

    @Override
    public Integer component2() {
        return getContainerId();
    }

    @Override
    public String component3() {
        return getAttributeValue();
    }

    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getAttributeId();
    }

    @Override
    public Integer value2() {
        return getContainerId();
    }

    @Override
    public String value3() {
        return getAttributeValue();
    }

    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    @Override
    public ContainerAttributesRecord value1(Integer value) {
        setAttributeId(value);
        return this;
    }

    @Override
    public ContainerAttributesRecord value2(Integer value) {
        setContainerId(value);
        return this;
    }

    @Override
    public ContainerAttributesRecord value3(String value) {
        setAttributeValue(value);
        return this;
    }

    @Override
    public ContainerAttributesRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ContainerAttributesRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ContainerAttributesRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainerAttributesRecord
     */
    public ContainerAttributesRecord() {
        super(ContainerAttributes.CONTAINER_ATTRIBUTES);
    }

    /**
     * Create a detached, initialised ContainerAttributesRecord
     */
    public ContainerAttributesRecord(Integer attributeId, Integer containerId, String attributeValue, Timestamp createdOn, Timestamp updatedOn) {
        super(ContainerAttributes.CONTAINER_ATTRIBUTES);

        setAttributeId(attributeId);
        setContainerId(containerId);
        setAttributeValue(attributeValue);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ContainerAttributesRecord
     */
    public ContainerAttributesRecord(jhi.seedstore.database.codegen.tables.pojos.ContainerAttributes value) {
        super(ContainerAttributes.CONTAINER_ATTRIBUTES);

        if (value != null) {
            setAttributeId(value.getAttributeId());
            setContainerId(value.getContainerId());
            setAttributeValue(value.getAttributeValue());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
