/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.Projects;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectsRecord extends UpdatableRecordImpl<ProjectsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.projects.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.projects.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.projects.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.projects.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.projects.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.projects.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stash_db.projects.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.projects.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>stash_db.projects.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.projects.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>stash_db.projects.end_date</code>.
     */
    public void setEndDate(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.projects.end_date</code>.
     */
    public Date getEndDate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>stash_db.projects.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.projects.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>stash_db.projects.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>stash_db.projects.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectsRecord
     */
    public ProjectsRecord() {
        super(Projects.PROJECTS);
    }

    /**
     * Create a detached, initialised ProjectsRecord
     */
    public ProjectsRecord(Integer id, String name, String description, Integer userId, Date startDate, Date endDate, Timestamp createdOn, Timestamp updatedOn) {
        super(Projects.PROJECTS);

        setId(id);
        setName(name);
        setDescription(description);
        setUserId(userId);
        setStartDate(startDate);
        setEndDate(endDate);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ProjectsRecord
     */
    public ProjectsRecord(jhi.seedstore.database.codegen.tables.pojos.Projects value) {
        super(Projects.PROJECTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setUserId(value.getUserId());
            setStartDate(value.getStartDate());
            setEndDate(value.getEndDate());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
