/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.TransferLogs;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransferLogsRecord extends UpdatableRecordImpl<TransferLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.transfer_logs.transfer_event_id</code>.
     */
    public void setTransferEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.transfer_event_id</code>.
     */
    public Integer getTransferEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.transfer_logs.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stash_db.transfer_logs.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>stash_db.transfer_logs.target_id</code>.
     */
    public void setTargetId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.target_id</code>.
     */
    public Integer getTargetId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>stash_db.transfer_logs.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>stash_db.transfer_logs.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>stash_db.transfer_logs.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.transfer_logs.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferLogsRecord
     */
    public TransferLogsRecord() {
        super(TransferLogs.TRANSFER_LOGS);
    }

    /**
     * Create a detached, initialised TransferLogsRecord
     */
    public TransferLogsRecord(Integer transferEventId, Integer containerId, Integer sourceId, Integer targetId, Integer userId, Timestamp createdOn, Timestamp updatedOn) {
        super(TransferLogs.TRANSFER_LOGS);

        setTransferEventId(transferEventId);
        setContainerId(containerId);
        setSourceId(sourceId);
        setTargetId(targetId);
        setUserId(userId);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TransferLogsRecord
     */
    public TransferLogsRecord(jhi.seedstore.database.codegen.tables.pojos.TransferLogs value) {
        super(TransferLogs.TRANSFER_LOGS);

        if (value != null) {
            setTransferEventId(value.getTransferEventId());
            setContainerId(value.getContainerId());
            setSourceId(value.getSourceId());
            setTargetId(value.getTargetId());
            setUserId(value.getUserId());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
