/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.Trials;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrialsRecord extends UpdatableRecordImpl<TrialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.trials.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.trials.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.trials.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.trials.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.trials.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.trials.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stash_db.trials.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.trials.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>stash_db.trials.row_count</code>.
     */
    public void setRowCount(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.trials.row_count</code>.
     */
    public Short getRowCount() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>stash_db.trials.column_count</code>.
     */
    public void setColumnCount(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.trials.column_count</code>.
     */
    public Short getColumnCount() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>stash_db.trials.shapefile</code>.
     */
    public void setShapefile(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.trials.shapefile</code>.
     */
    public byte[] getShapefile() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>stash_db.trials.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>stash_db.trials.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>stash_db.trials.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>stash_db.trials.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>stash_db.trials.end_date</code>.
     */
    public void setEndDate(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>stash_db.trials.end_date</code>.
     */
    public Date getEndDate() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>stash_db.trials.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>stash_db.trials.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>stash_db.trials.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>stash_db.trials.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrialsRecord
     */
    public TrialsRecord() {
        super(Trials.TRIALS);
    }

    /**
     * Create a detached, initialised TrialsRecord
     */
    public TrialsRecord(Integer id, String name, String description, Integer projectId, Short rowCount, Short columnCount, byte[] shapefile, Integer userId, Date startDate, Date endDate, Timestamp createdOn, Timestamp updatedOn) {
        super(Trials.TRIALS);

        setId(id);
        setName(name);
        setDescription(description);
        setProjectId(projectId);
        setRowCount(rowCount);
        setColumnCount(columnCount);
        setShapefile(shapefile);
        setUserId(userId);
        setStartDate(startDate);
        setEndDate(endDate);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TrialsRecord
     */
    public TrialsRecord(jhi.seedstore.database.codegen.tables.pojos.Trials value) {
        super(Trials.TRIALS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setProjectId(value.getProjectId());
            setRowCount(value.getRowCount());
            setColumnCount(value.getColumnCount());
            setShapefile(value.getShapefile());
            setUserId(value.getUserId());
            setStartDate(value.getStartDate());
            setEndDate(value.getEndDate());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
