/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.Trials;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrialsRecord extends UpdatableRecordImpl<TrialsRecord> implements Record12<Integer, String, String, Integer, Short, Short, byte[], Integer, Date, Date, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.trials.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seedstore_db.trials.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>seedstore_db.trials.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>seedstore_db.trials.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>seedstore_db.trials.row_count</code>.
     */
    public void setRowCount(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.row_count</code>.
     */
    public Short getRowCount() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>seedstore_db.trials.column_count</code>.
     */
    public void setColumnCount(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.column_count</code>.
     */
    public Short getColumnCount() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>seedstore_db.trials.shapefile</code>.
     */
    public void setShapefile(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.shapefile</code>.
     */
    public byte[] getShapefile() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>seedstore_db.trials.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>seedstore_db.trials.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>seedstore_db.trials.end_date</code>.
     */
    public void setEndDate(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.end_date</code>.
     */
    public Date getEndDate() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>seedstore_db.trials.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>seedstore_db.trials.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>seedstore_db.trials.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, Integer, Short, Short, byte[], Integer, Date, Date, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, Integer, Short, Short, byte[], Integer, Date, Date, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Trials.TRIALS.ID;
    }

    @Override
    public Field<String> field2() {
        return Trials.TRIALS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Trials.TRIALS.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Trials.TRIALS.PROJECT_ID;
    }

    @Override
    public Field<Short> field5() {
        return Trials.TRIALS.ROW_COUNT;
    }

    @Override
    public Field<Short> field6() {
        return Trials.TRIALS.COLUMN_COUNT;
    }

    @Override
    public Field<byte[]> field7() {
        return Trials.TRIALS.SHAPEFILE;
    }

    @Override
    public Field<Integer> field8() {
        return Trials.TRIALS.USER_ID;
    }

    @Override
    public Field<Date> field9() {
        return Trials.TRIALS.START_DATE;
    }

    @Override
    public Field<Date> field10() {
        return Trials.TRIALS.END_DATE;
    }

    @Override
    public Field<Timestamp> field11() {
        return Trials.TRIALS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field12() {
        return Trials.TRIALS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getProjectId();
    }

    @Override
    public Short component5() {
        return getRowCount();
    }

    @Override
    public Short component6() {
        return getColumnCount();
    }

    @Override
    public byte[] component7() {
        return getShapefile();
    }

    @Override
    public Integer component8() {
        return getUserId();
    }

    @Override
    public Date component9() {
        return getStartDate();
    }

    @Override
    public Date component10() {
        return getEndDate();
    }

    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component12() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getProjectId();
    }

    @Override
    public Short value5() {
        return getRowCount();
    }

    @Override
    public Short value6() {
        return getColumnCount();
    }

    @Override
    public byte[] value7() {
        return getShapefile();
    }

    @Override
    public Integer value8() {
        return getUserId();
    }

    @Override
    public Date value9() {
        return getStartDate();
    }

    @Override
    public Date value10() {
        return getEndDate();
    }

    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value12() {
        return getUpdatedOn();
    }

    @Override
    public TrialsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrialsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TrialsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TrialsRecord value4(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public TrialsRecord value5(Short value) {
        setRowCount(value);
        return this;
    }

    @Override
    public TrialsRecord value6(Short value) {
        setColumnCount(value);
        return this;
    }

    @Override
    public TrialsRecord value7(byte[] value) {
        setShapefile(value);
        return this;
    }

    @Override
    public TrialsRecord value8(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TrialsRecord value9(Date value) {
        setStartDate(value);
        return this;
    }

    @Override
    public TrialsRecord value10(Date value) {
        setEndDate(value);
        return this;
    }

    @Override
    public TrialsRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TrialsRecord value12(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public TrialsRecord values(Integer value1, String value2, String value3, Integer value4, Short value5, Short value6, byte[] value7, Integer value8, Date value9, Date value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrialsRecord
     */
    public TrialsRecord() {
        super(Trials.TRIALS);
    }

    /**
     * Create a detached, initialised TrialsRecord
     */
    public TrialsRecord(Integer id, String name, String description, Integer projectId, Short rowCount, Short columnCount, byte[] shapefile, Integer userId, Date startDate, Date endDate, Timestamp createdOn, Timestamp updatedOn) {
        super(Trials.TRIALS);

        setId(id);
        setName(name);
        setDescription(description);
        setProjectId(projectId);
        setRowCount(rowCount);
        setColumnCount(columnCount);
        setShapefile(shapefile);
        setUserId(userId);
        setStartDate(startDate);
        setEndDate(endDate);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised TrialsRecord
     */
    public TrialsRecord(jhi.seedstore.database.codegen.tables.pojos.Trials value) {
        super(Trials.TRIALS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setProjectId(value.getProjectId());
            setRowCount(value.getRowCount());
            setColumnCount(value.getColumnCount());
            setShapefile(value.getShapefile());
            setUserId(value.getUserId());
            setStartDate(value.getStartDate());
            setEndDate(value.getEndDate());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
