/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.enums.UsersUserType;
import jhi.seedstore.database.codegen.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.users.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.users.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stash_db.users.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stash_db.users.icon</code>.
     */
    public void setIcon(byte[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.users.icon</code>.
     */
    public byte[] getIcon() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>stash_db.users.user_type</code>.
     */
    public void setUserType(UsersUserType value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.users.user_type</code>.
     */
    public UsersUserType getUserType() {
        return (UsersUserType) get(5);
    }

    /**
     * Setter for <code>stash_db.users.last_login</code>.
     */
    public void setLastLogin(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.users.last_login</code>.
     */
    public Timestamp getLastLogin() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>stash_db.users.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>stash_db.users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>stash_db.users.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>stash_db.users.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, String emailAddress, String passwordHash, byte[] icon, UsersUserType userType, Timestamp lastLogin, Timestamp createdOn, Timestamp updatedOn) {
        super(Users.USERS);

        setId(id);
        setName(name);
        setEmailAddress(emailAddress);
        setPasswordHash(passwordHash);
        setIcon(icon);
        setUserType(userType);
        setLastLogin(lastLogin);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(jhi.seedstore.database.codegen.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmailAddress(value.getEmailAddress());
            setPasswordHash(value.getPasswordHash());
            setIcon(value.getIcon());
            setUserType(value.getUserType());
            setLastLogin(value.getLastLogin());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
