/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;
import java.util.Map;

import jhi.seedstore.database.codegen.enums.ViewTableUsersUserType;
import jhi.seedstore.database.codegen.tables.ViewTableUsers;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableUsersRecord extends TableRecordImpl<ViewTableUsersRecord> implements Record6<Integer, String, String, ViewTableUsersUserType, Timestamp, Map<String,Integer>> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.view_table_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seedstore_db.view_table_users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>seedstore_db.view_table_users.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_users.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>seedstore_db.view_table_users.user_type</code>.
     */
    public void setUserType(ViewTableUsersUserType value) {
        set(3, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_users.user_type</code>.
     */
    public ViewTableUsersUserType getUserType() {
        return (ViewTableUsersUserType) get(3);
    }

    /**
     * Setter for <code>seedstore_db.view_table_users.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>seedstore_db.view_table_users.stats</code>.
     */
    public void setStats(Map<String,Integer> value) {
        set(5, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_users.stats</code>.
     */
    public Map<String,Integer> getStats() {
        return (Map<String,Integer>) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, ViewTableUsersUserType, Timestamp, Map<String,Integer>> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, ViewTableUsersUserType, Timestamp, Map<String,Integer>> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewTableUsers.VIEW_TABLE_USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return ViewTableUsers.VIEW_TABLE_USERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return ViewTableUsers.VIEW_TABLE_USERS.EMAIL_ADDRESS;
    }

    @Override
    public Field<ViewTableUsersUserType> field4() {
        return ViewTableUsers.VIEW_TABLE_USERS.USER_TYPE;
    }

    @Override
    public Field<Timestamp> field5() {
        return ViewTableUsers.VIEW_TABLE_USERS.CREATED_ON;
    }

    @Override
    public Field<Map<String,Integer>> field6() {
        return ViewTableUsers.VIEW_TABLE_USERS.STATS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmailAddress();
    }

    @Override
    public ViewTableUsersUserType component4() {
        return getUserType();
    }

    @Override
    public Timestamp component5() {
        return getCreatedOn();
    }

    @Override
    public Map<String,Integer> component6() {
        return getStats();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmailAddress();
    }

    @Override
    public ViewTableUsersUserType value4() {
        return getUserType();
    }

    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    @Override
    public Map<String,Integer> value6() {
        return getStats();
    }

    @Override
    public ViewTableUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ViewTableUsersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ViewTableUsersRecord value3(String value) {
        setEmailAddress(value);
        return this;
    }

    @Override
    public ViewTableUsersRecord value4(ViewTableUsersUserType value) {
        setUserType(value);
        return this;
    }

    @Override
    public ViewTableUsersRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ViewTableUsersRecord value6(Map<String,Integer> value) {
        setStats(value);
        return this;
    }

    @Override
    public ViewTableUsersRecord values(Integer value1, String value2, String value3, ViewTableUsersUserType value4, Timestamp value5, Map<String,Integer> value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableUsersRecord
     */
    public ViewTableUsersRecord() {
        super(ViewTableUsers.VIEW_TABLE_USERS);
    }

    /**
     * Create a detached, initialised ViewTableUsersRecord
     */
    public ViewTableUsersRecord(Integer id, String name, String emailAddress, ViewTableUsersUserType userType, Timestamp createdOn, Map<String,Integer> stats) {
        super(ViewTableUsers.VIEW_TABLE_USERS);

        setId(id);
        setName(name);
        setEmailAddress(emailAddress);
        setUserType(userType);
        setCreatedOn(createdOn);
        setStats(stats);
    }

    /**
     * Create a detached, initialised ViewTableUsersRecord
     */
    public ViewTableUsersRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableUsers value) {
        super(ViewTableUsers.VIEW_TABLE_USERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmailAddress(value.getEmailAddress());
            setUserType(value.getUserType());
            setCreatedOn(value.getCreatedOn());
            setStats(value.getStats());
        }
    }
    // @formatter:on
}
