/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ViewTableTransfers;

import org.jooq.JSON;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTransfersRecord extends TableRecordImpl<ViewTableTransfersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.view_table_transfers.transfer_event_id</code>.
     */
    public void setTransferEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.transfer_event_id</code>.
     */
    public Integer getTransferEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.container_barcode</code>.
     */
    public void setContainerBarcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.container_barcode</code>.
     */
    public String getContainerBarcode() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>stash_db.view_table_transfers.container_attributes</code>.
     */
    public void setContainerAttributes(JSON value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>stash_db.view_table_transfers.container_attributes</code>.
     */
    public JSON getContainerAttributes() {
        return (JSON) get(3);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.source_barcode</code>.
     */
    public void setSourceBarcode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.source_barcode</code>.
     */
    public String getSourceBarcode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.source_attributes</code>.
     */
    public void setSourceAttributes(JSON value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.source_attributes</code>.
     */
    public JSON getSourceAttributes() {
        return (JSON) get(6);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.target_id</code>.
     */
    public void setTargetId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.target_id</code>.
     */
    public Integer getTargetId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.target_barcode</code>.
     */
    public void setTargetBarcode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.target_barcode</code>.
     */
    public String getTargetBarcode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.target_attributes</code>.
     */
    public void setTargetAttributes(JSON value) {
        set(9, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.target_attributes</code>.
     */
    public JSON getTargetAttributes() {
        return (JSON) get(9);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.user_name</code>.
     */
    public void setUserName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.user_name</code>.
     */
    public String getUserName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>stash_db.view_table_transfers.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>stash_db.view_table_transfers.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(13);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableTransfersRecord
     */
    public ViewTableTransfersRecord() {
        super(ViewTableTransfers.VIEW_TABLE_TRANSFERS);
    }

    /**
     * Create a detached, initialised ViewTableTransfersRecord
     */
    public ViewTableTransfersRecord(Integer transferEventId, Integer containerId, String containerBarcode, JSON containerAttributes, Integer sourceId, String sourceBarcode, JSON sourceAttributes, Integer targetId, String targetBarcode, JSON targetAttributes, Integer userId, String userName, Timestamp createdOn, Timestamp updatedOn) {
        super(ViewTableTransfers.VIEW_TABLE_TRANSFERS);

        setTransferEventId(transferEventId);
        setContainerId(containerId);
        setContainerBarcode(containerBarcode);
        setContainerAttributes(containerAttributes);
        setSourceId(sourceId);
        setSourceBarcode(sourceBarcode);
        setSourceAttributes(sourceAttributes);
        setTargetId(targetId);
        setTargetBarcode(targetBarcode);
        setTargetAttributes(targetAttributes);
        setUserId(userId);
        setUserName(userName);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewTableTransfersRecord
     */
    public ViewTableTransfersRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableTransfers value) {
        super(ViewTableTransfers.VIEW_TABLE_TRANSFERS);

        if (value != null) {
            setTransferEventId(value.getTransferEventId());
            setContainerId(value.getContainerId());
            setContainerBarcode(value.getContainerBarcode());
            setContainerAttributes(value.getContainerAttributes());
            setSourceId(value.getSourceId());
            setSourceBarcode(value.getSourceBarcode());
            setSourceAttributes(value.getSourceAttributes());
            setTargetId(value.getTargetId());
            setTargetBarcode(value.getTargetBarcode());
            setTargetAttributes(value.getTargetAttributes());
            setUserId(value.getUserId());
            setUserName(value.getUserName());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
