/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ViewTableContainers;
import jhi.seedstore.pojo.ContainerAttributeValue;

import org.jooq.Field;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableContainersRecord extends TableRecordImpl<ViewTableContainersRecord> implements Record20<Integer, String, String, Integer, String, String, String, Integer, String, String, Boolean, Integer, String, String, Integer, String, String, ContainerAttributeValue[], Long, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.view_table_containers.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_barcode</code>.
     */
    public void setContainerBarcode(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_barcode</code>.
     */
    public String getContainerBarcode() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_description</code>.
     */
    public void setContainerDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_description</code>.
     */
    public String getContainerDescription() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_id</code>.
     */
    public void setContainerTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_id</code>.
     */
    public Integer getContainerTypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_name</code>.
     */
    public void setContainerTypeName(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_name</code>.
     */
    public String getContainerTypeName() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_description</code>.
     */
    public void setContainerTypeDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_description</code>.
     */
    public String getContainerTypeDescription() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_icon</code>.
     */
    public void setContainerTypeIcon(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_icon</code>.
     */
    public String getContainerTypeIcon() {
        return (String) get(6);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_barcode</code>.
     */
    public void setParentBarcode(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_barcode</code>.
     */
    public String getParentBarcode() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_description</code>.
     */
    public void setParentDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_description</code>.
     */
    public String getParentDescription() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_is_active</code>.
     */
    public void setContainerIsActive(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_is_active</code>.
     */
    public Boolean getContainerIsActive() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.trial_id</code>.
     */
    public void setTrialId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.trial_id</code>.
     */
    public Integer getTrialId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.trial_name</code>.
     */
    public void setTrialName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.trial_name</code>.
     */
    public String getTrialName() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.trial_description</code>.
     */
    public void setTrialDescription(String value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.trial_description</code>.
     */
    public String getTrialDescription() {
        return (String) get(13);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.project_name</code>.
     */
    public void setProjectName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.project_name</code>.
     */
    public String getProjectName() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.project_description</code>.
     */
    public void setProjectDescription(String value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.project_description</code>.
     */
    public String getProjectDescription() {
        return (String) get(16);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_attributes</code>.
     */
    public void setContainerAttributes(ContainerAttributeValue[] value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_attributes</code>.
     */
    public ContainerAttributeValue[] getContainerAttributes() {
        return (ContainerAttributeValue[]) get(17);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.sub_container_count</code>.
     */
    public void setSubContainerCount(Long value) {
        set(18, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.sub_container_count</code>.
     */
    public Long getSubContainerCount() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(19);
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<Integer, String, String, Integer, String, String, String, Integer, String, String, Boolean, Integer, String, String, Integer, String, String, ContainerAttributeValue[], Long, Timestamp> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<Integer, String, String, Integer, String, String, String, Integer, String, String, Boolean, Integer, String, String, Integer, String, String, ContainerAttributeValue[], Long, Timestamp> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_ID;
    }

    @Override
    public Field<String> field2() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_BARCODE;
    }

    @Override
    public Field<String> field3() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_TYPE_ID;
    }

    @Override
    public Field<String> field5() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_TYPE_NAME;
    }

    @Override
    public Field<String> field6() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_TYPE_DESCRIPTION;
    }

    @Override
    public Field<String> field7() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_TYPE_ICON;
    }

    @Override
    public Field<Integer> field8() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.PARENT_ID;
    }

    @Override
    public Field<String> field9() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.PARENT_BARCODE;
    }

    @Override
    public Field<String> field10() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.PARENT_DESCRIPTION;
    }

    @Override
    public Field<Boolean> field11() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_IS_ACTIVE;
    }

    @Override
    public Field<Integer> field12() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.TRIAL_ID;
    }

    @Override
    public Field<String> field13() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.TRIAL_NAME;
    }

    @Override
    public Field<String> field14() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.TRIAL_DESCRIPTION;
    }

    @Override
    public Field<Integer> field15() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.PROJECT_ID;
    }

    @Override
    public Field<String> field16() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.PROJECT_NAME;
    }

    @Override
    public Field<String> field17() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.PROJECT_DESCRIPTION;
    }

    @Override
    public Field<ContainerAttributeValue[]> field18() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CONTAINER_ATTRIBUTES;
    }

    @Override
    public Field<Long> field19() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.SUB_CONTAINER_COUNT;
    }

    @Override
    public Field<Timestamp> field20() {
        return ViewTableContainers.VIEW_TABLE_CONTAINERS.CREATED_ON;
    }

    @Override
    public Integer component1() {
        return getContainerId();
    }

    @Override
    public String component2() {
        return getContainerBarcode();
    }

    @Override
    public String component3() {
        return getContainerDescription();
    }

    @Override
    public Integer component4() {
        return getContainerTypeId();
    }

    @Override
    public String component5() {
        return getContainerTypeName();
    }

    @Override
    public String component6() {
        return getContainerTypeDescription();
    }

    @Override
    public String component7() {
        return getContainerTypeIcon();
    }

    @Override
    public Integer component8() {
        return getParentId();
    }

    @Override
    public String component9() {
        return getParentBarcode();
    }

    @Override
    public String component10() {
        return getParentDescription();
    }

    @Override
    public Boolean component11() {
        return getContainerIsActive();
    }

    @Override
    public Integer component12() {
        return getTrialId();
    }

    @Override
    public String component13() {
        return getTrialName();
    }

    @Override
    public String component14() {
        return getTrialDescription();
    }

    @Override
    public Integer component15() {
        return getProjectId();
    }

    @Override
    public String component16() {
        return getProjectName();
    }

    @Override
    public String component17() {
        return getProjectDescription();
    }

    @Override
    public ContainerAttributeValue[] component18() {
        return getContainerAttributes();
    }

    @Override
    public Long component19() {
        return getSubContainerCount();
    }

    @Override
    public Timestamp component20() {
        return getCreatedOn();
    }

    @Override
    public Integer value1() {
        return getContainerId();
    }

    @Override
    public String value2() {
        return getContainerBarcode();
    }

    @Override
    public String value3() {
        return getContainerDescription();
    }

    @Override
    public Integer value4() {
        return getContainerTypeId();
    }

    @Override
    public String value5() {
        return getContainerTypeName();
    }

    @Override
    public String value6() {
        return getContainerTypeDescription();
    }

    @Override
    public String value7() {
        return getContainerTypeIcon();
    }

    @Override
    public Integer value8() {
        return getParentId();
    }

    @Override
    public String value9() {
        return getParentBarcode();
    }

    @Override
    public String value10() {
        return getParentDescription();
    }

    @Override
    public Boolean value11() {
        return getContainerIsActive();
    }

    @Override
    public Integer value12() {
        return getTrialId();
    }

    @Override
    public String value13() {
        return getTrialName();
    }

    @Override
    public String value14() {
        return getTrialDescription();
    }

    @Override
    public Integer value15() {
        return getProjectId();
    }

    @Override
    public String value16() {
        return getProjectName();
    }

    @Override
    public String value17() {
        return getProjectDescription();
    }

    @Override
    public ContainerAttributeValue[] value18() {
        return getContainerAttributes();
    }

    @Override
    public Long value19() {
        return getSubContainerCount();
    }

    @Override
    public Timestamp value20() {
        return getCreatedOn();
    }

    @Override
    public ViewTableContainersRecord value1(Integer value) {
        setContainerId(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value2(String value) {
        setContainerBarcode(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value3(String value) {
        setContainerDescription(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value4(Integer value) {
        setContainerTypeId(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value5(String value) {
        setContainerTypeName(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value6(String value) {
        setContainerTypeDescription(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value7(String value) {
        setContainerTypeIcon(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value8(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value9(String value) {
        setParentBarcode(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value10(String value) {
        setParentDescription(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value11(Boolean value) {
        setContainerIsActive(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value12(Integer value) {
        setTrialId(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value13(String value) {
        setTrialName(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value14(String value) {
        setTrialDescription(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value15(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value16(String value) {
        setProjectName(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value17(String value) {
        setProjectDescription(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value18(ContainerAttributeValue[] value) {
        setContainerAttributes(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value19(Long value) {
        setSubContainerCount(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord value20(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ViewTableContainersRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, Integer value8, String value9, String value10, Boolean value11, Integer value12, String value13, String value14, Integer value15, String value16, String value17, ContainerAttributeValue[] value18, Long value19, Timestamp value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableContainersRecord
     */
    public ViewTableContainersRecord() {
        super(ViewTableContainers.VIEW_TABLE_CONTAINERS);
    }

    /**
     * Create a detached, initialised ViewTableContainersRecord
     */
    public ViewTableContainersRecord(Integer containerId, String containerBarcode, String containerDescription, Integer containerTypeId, String containerTypeName, String containerTypeDescription, String containerTypeIcon, Integer parentId, String parentBarcode, String parentDescription, Boolean containerIsActive, Integer trialId, String trialName, String trialDescription, Integer projectId, String projectName, String projectDescription, ContainerAttributeValue[] containerAttributes, Long subContainerCount, Timestamp createdOn) {
        super(ViewTableContainers.VIEW_TABLE_CONTAINERS);

        setContainerId(containerId);
        setContainerBarcode(containerBarcode);
        setContainerDescription(containerDescription);
        setContainerTypeId(containerTypeId);
        setContainerTypeName(containerTypeName);
        setContainerTypeDescription(containerTypeDescription);
        setContainerTypeIcon(containerTypeIcon);
        setParentId(parentId);
        setParentBarcode(parentBarcode);
        setParentDescription(parentDescription);
        setContainerIsActive(containerIsActive);
        setTrialId(trialId);
        setTrialName(trialName);
        setTrialDescription(trialDescription);
        setProjectId(projectId);
        setProjectName(projectName);
        setProjectDescription(projectDescription);
        setContainerAttributes(containerAttributes);
        setSubContainerCount(subContainerCount);
        setCreatedOn(createdOn);
    }

    /**
     * Create a detached, initialised ViewTableContainersRecord
     */
    public ViewTableContainersRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableContainers value) {
        super(ViewTableContainers.VIEW_TABLE_CONTAINERS);

        if (value != null) {
            setContainerId(value.getContainerId());
            setContainerBarcode(value.getContainerBarcode());
            setContainerDescription(value.getContainerDescription());
            setContainerTypeId(value.getContainerTypeId());
            setContainerTypeName(value.getContainerTypeName());
            setContainerTypeDescription(value.getContainerTypeDescription());
            setContainerTypeIcon(value.getContainerTypeIcon());
            setParentId(value.getParentId());
            setParentBarcode(value.getParentBarcode());
            setParentDescription(value.getParentDescription());
            setContainerIsActive(value.getContainerIsActive());
            setTrialId(value.getTrialId());
            setTrialName(value.getTrialName());
            setTrialDescription(value.getTrialDescription());
            setProjectId(value.getProjectId());
            setProjectName(value.getProjectName());
            setProjectDescription(value.getProjectDescription());
            setContainerAttributes(value.getContainerAttributes());
            setSubContainerCount(value.getSubContainerCount());
            setCreatedOn(value.getCreatedOn());
        }
    }
    // @formatter:on
}
