/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ViewTableTransfers;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableTransfersRecord extends TableRecordImpl<ViewTableTransfersRecord> implements Record13<Integer, Integer, String, String, Integer, String, String, Integer, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfers.transfer_log_id</code>.
     */
    public void setTransferLogId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfers.transfer_log_id</code>.
     */
    public Integer getTransferLogId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfers.container_barcode</code>.
     */
    public void setContainerBarcode(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfers.container_barcode</code>.
     */
    public String getContainerBarcode() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfers.container_description</code>.
     */
    public void setContainerDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfers.container_description</code>.
     */
    public String getContainerDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.source_barcode</code>.
     */
    public void setSourceBarcode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.source_barcode</code>.
     */
    public String getSourceBarcode() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfers.source_description</code>.
     */
    public void setSourceDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfers.source_description</code>.
     */
    public String getSourceDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.target_id</code>.
     */
    public void setTargetId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.target_id</code>.
     */
    public Integer getTargetId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.target_barcode</code>.
     */
    public void setTargetBarcode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.target_barcode</code>.
     */
    public String getTargetBarcode() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfers.target_description</code>.
     */
    public void setTargetDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfers.target_description</code>.
     */
    public String getTargetDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfers.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfers.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, String, String, Integer, String, String, Integer, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, String, String, Integer, String, String, Integer, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.TRANSFER_LOG_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.CONTAINER_ID;
    }

    @Override
    public Field<String> field3() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.CONTAINER_BARCODE;
    }

    @Override
    public Field<String> field4() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.CONTAINER_DESCRIPTION;
    }

    @Override
    public Field<Integer> field5() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.SOURCE_ID;
    }

    @Override
    public Field<String> field6() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.SOURCE_BARCODE;
    }

    @Override
    public Field<String> field7() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.SOURCE_DESCRIPTION;
    }

    @Override
    public Field<Integer> field8() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.TARGET_ID;
    }

    @Override
    public Field<String> field9() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.TARGET_BARCODE;
    }

    @Override
    public Field<String> field10() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.TARGET_DESCRIPTION;
    }

    @Override
    public Field<Integer> field11() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.USER_ID;
    }

    @Override
    public Field<Timestamp> field12() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field13() {
        return ViewTableTransfers.VIEW_TABLE_TRANSFERS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getTransferLogId();
    }

    @Override
    public Integer component2() {
        return getContainerId();
    }

    @Override
    public String component3() {
        return getContainerBarcode();
    }

    @Override
    public String component4() {
        return getContainerDescription();
    }

    @Override
    public Integer component5() {
        return getSourceId();
    }

    @Override
    public String component6() {
        return getSourceBarcode();
    }

    @Override
    public String component7() {
        return getSourceDescription();
    }

    @Override
    public Integer component8() {
        return getTargetId();
    }

    @Override
    public String component9() {
        return getTargetBarcode();
    }

    @Override
    public String component10() {
        return getTargetDescription();
    }

    @Override
    public Integer component11() {
        return getUserId();
    }

    @Override
    public Timestamp component12() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component13() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getTransferLogId();
    }

    @Override
    public Integer value2() {
        return getContainerId();
    }

    @Override
    public String value3() {
        return getContainerBarcode();
    }

    @Override
    public String value4() {
        return getContainerDescription();
    }

    @Override
    public Integer value5() {
        return getSourceId();
    }

    @Override
    public String value6() {
        return getSourceBarcode();
    }

    @Override
    public String value7() {
        return getSourceDescription();
    }

    @Override
    public Integer value8() {
        return getTargetId();
    }

    @Override
    public String value9() {
        return getTargetBarcode();
    }

    @Override
    public String value10() {
        return getTargetDescription();
    }

    @Override
    public Integer value11() {
        return getUserId();
    }

    @Override
    public Timestamp value12() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value13() {
        return getUpdatedOn();
    }

    @Override
    public ViewTableTransfersRecord value1(Integer value) {
        setTransferLogId(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value2(Integer value) {
        setContainerId(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value3(String value) {
        setContainerBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value4(String value) {
        setContainerDescription(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value5(Integer value) {
        setSourceId(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value6(String value) {
        setSourceBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value7(String value) {
        setSourceDescription(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value8(Integer value) {
        setTargetId(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value9(String value) {
        setTargetBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value10(String value) {
        setTargetDescription(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value11(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value12(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord value13(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ViewTableTransfersRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, Integer value8, String value9, String value10, Integer value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableTransfersRecord
     */
    public ViewTableTransfersRecord() {
        super(ViewTableTransfers.VIEW_TABLE_TRANSFERS);
    }

    /**
     * Create a detached, initialised ViewTableTransfersRecord
     */
    public ViewTableTransfersRecord(Integer transferLogId, Integer containerId, String containerBarcode, String containerDescription, Integer sourceId, String sourceBarcode, String sourceDescription, Integer targetId, String targetBarcode, String targetDescription, Integer userId, Timestamp createdOn, Timestamp updatedOn) {
        super(ViewTableTransfers.VIEW_TABLE_TRANSFERS);

        setTransferLogId(transferLogId);
        setContainerId(containerId);
        setContainerBarcode(containerBarcode);
        setContainerDescription(containerDescription);
        setSourceId(sourceId);
        setSourceBarcode(sourceBarcode);
        setSourceDescription(sourceDescription);
        setTargetId(targetId);
        setTargetBarcode(targetBarcode);
        setTargetDescription(targetDescription);
        setUserId(userId);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ViewTableTransfersRecord
     */
    public ViewTableTransfersRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableTransfers value) {
        super(ViewTableTransfers.VIEW_TABLE_TRANSFERS);

        if (value != null) {
            setTransferLogId(value.getTransferLogId());
            setContainerId(value.getContainerId());
            setContainerBarcode(value.getContainerBarcode());
            setContainerDescription(value.getContainerDescription());
            setSourceId(value.getSourceId());
            setSourceBarcode(value.getSourceBarcode());
            setSourceDescription(value.getSourceDescription());
            setTargetId(value.getTargetId());
            setTargetBarcode(value.getTargetBarcode());
            setTargetDescription(value.getTargetDescription());
            setUserId(value.getUserId());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
