/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ViewTableTransferEvents;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableTransferEventsRecord extends TableRecordImpl<ViewTableTransferEventsRecord> implements Record12<String, Timestamp, Integer, String, String, Integer, String, String, Integer, String, Long, Integer[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.view_table_transfer_events.event_id</code>.
     */
    public void setEventId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfer_events.event_id</code>.
     */
    public String getEventId() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.source_barcode</code>.
     */
    public void setSourceBarcode(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.source_barcode</code>.
     */
    public String getSourceBarcode() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.source_type</code>.
     */
    public void setSourceType(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.source_type</code>.
     */
    public String getSourceType() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.target_id</code>.
     */
    public void setTargetId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.target_id</code>.
     */
    public Integer getTargetId() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.target_barcode</code>.
     */
    public void setTargetBarcode(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.target_barcode</code>.
     */
    public String getTargetBarcode() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.target_type</code>.
     */
    public void setTargetType(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.target_type</code>.
     */
    public String getTargetType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfer_events.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfer_events.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(8);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.user_name</code>.
     */
    public void setUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.user_name</code>.
     */
    public String getUserName() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.container_count</code>.
     */
    public void setContainerCount(Long value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.container_count</code>.
     */
    public Long getContainerCount() {
        return (Long) get(10);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.container_ids</code>.
     */
    public void setContainerIds(Integer[] value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.container_ids</code>.
     */
    public Integer[] getContainerIds() {
        return (Integer[]) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, Timestamp, Integer, String, String, Integer, String, String, Integer, String, Long, Integer[]> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, Timestamp, Integer, String, String, Integer, String, String, Integer, String, Long, Integer[]> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.EVENT_ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TIMESTAMP;
    }

    @Override
    public Field<Integer> field3() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.SOURCE_ID;
    }

    @Override
    public Field<String> field4() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.SOURCE_BARCODE;
    }

    @Override
    public Field<String> field5() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.SOURCE_TYPE;
    }

    @Override
    public Field<Integer> field6() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TARGET_ID;
    }

    @Override
    public Field<String> field7() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TARGET_BARCODE;
    }

    @Override
    public Field<String> field8() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TARGET_TYPE;
    }

    @Override
    public Field<Integer> field9() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.USER_ID;
    }

    @Override
    public Field<String> field10() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.USER_NAME;
    }

    @Override
    public Field<Long> field11() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.CONTAINER_COUNT;
    }

    @Override
    public Field<Integer[]> field12() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.CONTAINER_IDS;
    }

    @Override
    public String component1() {
        return getEventId();
    }

    @Override
    public Timestamp component2() {
        return getTimestamp();
    }

    @Override
    public Integer component3() {
        return getSourceId();
    }

    @Override
    public String component4() {
        return getSourceBarcode();
    }

    @Override
    public String component5() {
        return getSourceType();
    }

    @Override
    public Integer component6() {
        return getTargetId();
    }

    @Override
    public String component7() {
        return getTargetBarcode();
    }

    @Override
    public String component8() {
        return getTargetType();
    }

    @Override
    public Integer component9() {
        return getUserId();
    }

    @Override
    public String component10() {
        return getUserName();
    }

    @Override
    public Long component11() {
        return getContainerCount();
    }

    @Override
    public Integer[] component12() {
        return getContainerIds();
    }

    @Override
    public String value1() {
        return getEventId();
    }

    @Override
    public Timestamp value2() {
        return getTimestamp();
    }

    @Override
    public Integer value3() {
        return getSourceId();
    }

    @Override
    public String value4() {
        return getSourceBarcode();
    }

    @Override
    public String value5() {
        return getSourceType();
    }

    @Override
    public Integer value6() {
        return getTargetId();
    }

    @Override
    public String value7() {
        return getTargetBarcode();
    }

    @Override
    public String value8() {
        return getTargetType();
    }

    @Override
    public Integer value9() {
        return getUserId();
    }

    @Override
    public String value10() {
        return getUserName();
    }

    @Override
    public Long value11() {
        return getContainerCount();
    }

    @Override
    public Integer[] value12() {
        return getContainerIds();
    }

    @Override
    public ViewTableTransferEventsRecord value1(String value) {
        setEventId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value2(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value3(Integer value) {
        setSourceId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value4(String value) {
        setSourceBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value5(String value) {
        setSourceType(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value6(Integer value) {
        setTargetId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value7(String value) {
        setTargetBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value8(String value) {
        setTargetType(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value9(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value10(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value11(Long value) {
        setContainerCount(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value12(Integer[] value) {
        setContainerIds(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord values(String value1, Timestamp value2, Integer value3, String value4, String value5, Integer value6, String value7, String value8, Integer value9, String value10, Long value11, Integer[] value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableTransferEventsRecord
     */
    public ViewTableTransferEventsRecord() {
        super(ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS);
    }

    /**
     * Create a detached, initialised ViewTableTransferEventsRecord
     */
    public ViewTableTransferEventsRecord(String eventId, Timestamp timestamp, Integer sourceId, String sourceBarcode, String sourceType, Integer targetId, String targetBarcode, String targetType, Integer userId, String userName, Long containerCount, Integer[] containerIds) {
        super(ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS);

        setEventId(eventId);
        setTimestamp(timestamp);
        setSourceId(sourceId);
        setSourceBarcode(sourceBarcode);
        setSourceType(sourceType);
        setTargetId(targetId);
        setTargetBarcode(targetBarcode);
        setTargetType(targetType);
        setUserId(userId);
        setUserName(userName);
        setContainerCount(containerCount);
        setContainerIds(containerIds);
    }

    /**
     * Create a detached, initialised ViewTableTransferEventsRecord
     */
    public ViewTableTransferEventsRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableTransferEvents value) {
        super(ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS);

        if (value != null) {
            setEventId(value.getEventId());
            setTimestamp(value.getTimestamp());
            setSourceId(value.getSourceId());
            setSourceBarcode(value.getSourceBarcode());
            setSourceType(value.getSourceType());
            setTargetId(value.getTargetId());
            setTargetBarcode(value.getTargetBarcode());
            setTargetType(value.getTargetType());
            setUserId(value.getUserId());
            setUserName(value.getUserName());
            setContainerCount(value.getContainerCount());
            setContainerIds(value.getContainerIds());
        }
    }
    // @formatter:on
}
