/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;
import java.util.Map;

import jhi.seedstore.database.codegen.enums.ViewTableUsersUserType;
import jhi.seedstore.database.codegen.tables.ViewTableUsers;

import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableUsersRecord extends TableRecordImpl<ViewTableUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stash_db.view_table_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stash_db.view_table_users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stash_db.view_table_users.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stash_db.view_table_users.user_type</code>.
     */
    public void setUserType(ViewTableUsersUserType value) {
        set(3, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.user_type</code>.
     */
    public ViewTableUsersUserType getUserType() {
        return (ViewTableUsersUserType) get(3);
    }

    /**
     * Setter for <code>stash_db.view_table_users.last_login</code>.
     */
    public void setLastLogin(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.last_login</code>.
     */
    public Timestamp getLastLogin() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>stash_db.view_table_users.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>stash_db.view_table_users.stats</code>.
     */
    public void setStats(Map<String,Integer> value) {
        set(6, value);
    }

    /**
     * Getter for <code>stash_db.view_table_users.stats</code>.
     */
    public Map<String,Integer> getStats() {
        return (Map<String,Integer>) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableUsersRecord
     */
    public ViewTableUsersRecord() {
        super(ViewTableUsers.VIEW_TABLE_USERS);
    }

    /**
     * Create a detached, initialised ViewTableUsersRecord
     */
    public ViewTableUsersRecord(Integer id, String name, String emailAddress, ViewTableUsersUserType userType, Timestamp lastLogin, Timestamp createdOn, Map<String,Integer> stats) {
        super(ViewTableUsers.VIEW_TABLE_USERS);

        setId(id);
        setName(name);
        setEmailAddress(emailAddress);
        setUserType(userType);
        setLastLogin(lastLogin);
        setCreatedOn(createdOn);
        setStats(stats);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewTableUsersRecord
     */
    public ViewTableUsersRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableUsers value) {
        super(ViewTableUsers.VIEW_TABLE_USERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmailAddress(value.getEmailAddress());
            setUserType(value.getUserType());
            setLastLogin(value.getLastLogin());
            setCreatedOn(value.getCreatedOn());
            setStats(value.getStats());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
