/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Date;

import jhi.seedstore.database.codegen.tables.ViewTableTransferEvents;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableTransferEventsRecord extends TableRecordImpl<ViewTableTransferEventsRecord> implements Record9<Date, Integer, String, String, Integer, String, String, Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.view_table_transfer_events.date</code>.
     */
    public void setDate(Date value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfer_events.date</code>.
     */
    public Date getDate() {
        return (Date) get(0);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.source_barcode</code>.
     */
    public void setSourceBarcode(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.source_barcode</code>.
     */
    public String getSourceBarcode() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.source_type</code>.
     */
    public void setSourceType(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.source_type</code>.
     */
    public String getSourceType() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.target_id</code>.
     */
    public void setTargetId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.target_id</code>.
     */
    public Integer getTargetId() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.target_barcode</code>.
     */
    public void setTargetBarcode(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.target_barcode</code>.
     */
    public String getTargetBarcode() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.target_type</code>.
     */
    public void setTargetType(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.target_type</code>.
     */
    public String getTargetType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>seedstore_db.view_table_transfer_events.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_transfer_events.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_transfer_events.container_count</code>.
     */
    public void setContainerCount(Long value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_transfer_events.container_count</code>.
     */
    public Long getContainerCount() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Date, Integer, String, String, Integer, String, String, Integer, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Date, Integer, String, String, Integer, String, String, Integer, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Date> field1() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.DATE;
    }

    @Override
    public Field<Integer> field2() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.SOURCE_ID;
    }

    @Override
    public Field<String> field3() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.SOURCE_BARCODE;
    }

    @Override
    public Field<String> field4() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.SOURCE_TYPE;
    }

    @Override
    public Field<Integer> field5() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TARGET_ID;
    }

    @Override
    public Field<String> field6() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TARGET_BARCODE;
    }

    @Override
    public Field<String> field7() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.TARGET_TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.USER_ID;
    }

    @Override
    public Field<Long> field9() {
        return ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS.CONTAINER_COUNT;
    }

    @Override
    public Date component1() {
        return getDate();
    }

    @Override
    public Integer component2() {
        return getSourceId();
    }

    @Override
    public String component3() {
        return getSourceBarcode();
    }

    @Override
    public String component4() {
        return getSourceType();
    }

    @Override
    public Integer component5() {
        return getTargetId();
    }

    @Override
    public String component6() {
        return getTargetBarcode();
    }

    @Override
    public String component7() {
        return getTargetType();
    }

    @Override
    public Integer component8() {
        return getUserId();
    }

    @Override
    public Long component9() {
        return getContainerCount();
    }

    @Override
    public Date value1() {
        return getDate();
    }

    @Override
    public Integer value2() {
        return getSourceId();
    }

    @Override
    public String value3() {
        return getSourceBarcode();
    }

    @Override
    public String value4() {
        return getSourceType();
    }

    @Override
    public Integer value5() {
        return getTargetId();
    }

    @Override
    public String value6() {
        return getTargetBarcode();
    }

    @Override
    public String value7() {
        return getTargetType();
    }

    @Override
    public Integer value8() {
        return getUserId();
    }

    @Override
    public Long value9() {
        return getContainerCount();
    }

    @Override
    public ViewTableTransferEventsRecord value1(Date value) {
        setDate(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value2(Integer value) {
        setSourceId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value3(String value) {
        setSourceBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value4(String value) {
        setSourceType(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value5(Integer value) {
        setTargetId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value6(String value) {
        setTargetBarcode(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value7(String value) {
        setTargetType(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value8(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord value9(Long value) {
        setContainerCount(value);
        return this;
    }

    @Override
    public ViewTableTransferEventsRecord values(Date value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, Integer value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableTransferEventsRecord
     */
    public ViewTableTransferEventsRecord() {
        super(ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS);
    }

    /**
     * Create a detached, initialised ViewTableTransferEventsRecord
     */
    public ViewTableTransferEventsRecord(Date date, Integer sourceId, String sourceBarcode, String sourceType, Integer targetId, String targetBarcode, String targetType, Integer userId, Long containerCount) {
        super(ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS);

        setDate(date);
        setSourceId(sourceId);
        setSourceBarcode(sourceBarcode);
        setSourceType(sourceType);
        setTargetId(targetId);
        setTargetBarcode(targetBarcode);
        setTargetType(targetType);
        setUserId(userId);
        setContainerCount(containerCount);
    }

    /**
     * Create a detached, initialised ViewTableTransferEventsRecord
     */
    public ViewTableTransferEventsRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableTransferEvents value) {
        super(ViewTableTransferEvents.VIEW_TABLE_TRANSFER_EVENTS);

        if (value != null) {
            setDate(value.getDate());
            setSourceId(value.getSourceId());
            setSourceBarcode(value.getSourceBarcode());
            setSourceType(value.getSourceType());
            setTargetId(value.getTargetId());
            setTargetBarcode(value.getTargetBarcode());
            setTargetType(value.getTargetType());
            setUserId(value.getUserId());
            setContainerCount(value.getContainerCount());
        }
    }
    // @formatter:on
}
