/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.seedstore.database.codegen.tables.ViewTableContainers;
import jhi.seedstore.pojo.ContainerAttributeValue;

import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableContainersRecord extends TableRecordImpl<ViewTableContainersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>seedstore_db.view_table_containers.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_barcode</code>.
     */
    public void setContainerBarcode(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_barcode</code>.
     */
    public String getContainerBarcode() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_description</code>.
     */
    public void setContainerDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_description</code>.
     */
    public String getContainerDescription() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_id</code>.
     */
    public void setContainerTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_id</code>.
     */
    public Integer getContainerTypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_name</code>.
     */
    public void setContainerTypeName(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_name</code>.
     */
    public String getContainerTypeName() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_description</code>.
     */
    public void setContainerTypeDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_description</code>.
     */
    public String getContainerTypeDescription() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_type_icon</code>.
     */
    public void setContainerTypeIcon(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_type_icon</code>.
     */
    public byte[] getContainerTypeIcon() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_barcode</code>.
     */
    public void setParentBarcode(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_barcode</code>.
     */
    public String getParentBarcode() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_description</code>.
     */
    public void setParentDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_description</code>.
     */
    public String getParentDescription() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_container_type_id</code>.
     */
    public void setParentContainerTypeId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_container_type_id</code>.
     */
    public Integer getParentContainerTypeId() {
        return (Integer) get(10);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_container_type_name</code>.
     */
    public void setParentContainerTypeName(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_container_type_name</code>.
     */
    public String getParentContainerTypeName() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_container_type_description</code>.
     */
    public void setParentContainerTypeDescription(String value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_container_type_description</code>.
     */
    public String getParentContainerTypeDescription() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.parent_container_type_icon</code>.
     */
    public void setParentContainerTypeIcon(byte[] value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.parent_container_type_icon</code>.
     */
    public byte[] getParentContainerTypeIcon() {
        return (byte[]) get(13);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_is_active</code>.
     */
    public void setContainerIsActive(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_is_active</code>.
     */
    public Boolean getContainerIsActive() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.trial_id</code>.
     */
    public void setTrialId(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.trial_id</code>.
     */
    public Integer getTrialId() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.trial_name</code>.
     */
    public void setTrialName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.trial_name</code>.
     */
    public String getTrialName() {
        return (String) get(16);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.trial_description</code>.
     */
    public void setTrialDescription(String value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.trial_description</code>.
     */
    public String getTrialDescription() {
        return (String) get(17);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.project_name</code>.
     */
    public void setProjectName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.project_name</code>.
     */
    public String getProjectName() {
        return (String) get(19);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.project_description</code>.
     */
    public void setProjectDescription(String value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.project_description</code>.
     */
    public String getProjectDescription() {
        return (String) get(20);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.container_attributes</code>.
     */
    public void setContainerAttributes(ContainerAttributeValue[] value) {
        set(21, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.container_attributes</code>.
     */
    public ContainerAttributeValue[] getContainerAttributes() {
        return (ContainerAttributeValue[]) get(21);
    }

    /**
     * Setter for
     * <code>seedstore_db.view_table_containers.sub_container_count</code>.
     */
    public void setSubContainerCount(Long value) {
        set(22, value);
    }

    /**
     * Getter for
     * <code>seedstore_db.view_table_containers.sub_container_count</code>.
     */
    public Long getSubContainerCount() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>seedstore_db.view_table_containers.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(23, value);
    }

    /**
     * Getter for <code>seedstore_db.view_table_containers.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(23);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableContainersRecord
     */
    public ViewTableContainersRecord() {
        super(ViewTableContainers.VIEW_TABLE_CONTAINERS);
    }

    /**
     * Create a detached, initialised ViewTableContainersRecord
     */
    public ViewTableContainersRecord(Integer containerId, String containerBarcode, String containerDescription, Integer containerTypeId, String containerTypeName, String containerTypeDescription, byte[] containerTypeIcon, Integer parentId, String parentBarcode, String parentDescription, Integer parentContainerTypeId, String parentContainerTypeName, String parentContainerTypeDescription, byte[] parentContainerTypeIcon, Boolean containerIsActive, Integer trialId, String trialName, String trialDescription, Integer projectId, String projectName, String projectDescription, ContainerAttributeValue[] containerAttributes, Long subContainerCount, Timestamp createdOn) {
        super(ViewTableContainers.VIEW_TABLE_CONTAINERS);

        setContainerId(containerId);
        setContainerBarcode(containerBarcode);
        setContainerDescription(containerDescription);
        setContainerTypeId(containerTypeId);
        setContainerTypeName(containerTypeName);
        setContainerTypeDescription(containerTypeDescription);
        setContainerTypeIcon(containerTypeIcon);
        setParentId(parentId);
        setParentBarcode(parentBarcode);
        setParentDescription(parentDescription);
        setParentContainerTypeId(parentContainerTypeId);
        setParentContainerTypeName(parentContainerTypeName);
        setParentContainerTypeDescription(parentContainerTypeDescription);
        setParentContainerTypeIcon(parentContainerTypeIcon);
        setContainerIsActive(containerIsActive);
        setTrialId(trialId);
        setTrialName(trialName);
        setTrialDescription(trialDescription);
        setProjectId(projectId);
        setProjectName(projectName);
        setProjectDescription(projectDescription);
        setContainerAttributes(containerAttributes);
        setSubContainerCount(subContainerCount);
        setCreatedOn(createdOn);
    }

    /**
     * Create a detached, initialised ViewTableContainersRecord
     */
    public ViewTableContainersRecord(jhi.seedstore.database.codegen.tables.pojos.ViewTableContainers value) {
        super(ViewTableContainers.VIEW_TABLE_CONTAINERS);

        if (value != null) {
            setContainerId(value.getContainerId());
            setContainerBarcode(value.getContainerBarcode());
            setContainerDescription(value.getContainerDescription());
            setContainerTypeId(value.getContainerTypeId());
            setContainerTypeName(value.getContainerTypeName());
            setContainerTypeDescription(value.getContainerTypeDescription());
            setContainerTypeIcon(value.getContainerTypeIcon());
            setParentId(value.getParentId());
            setParentBarcode(value.getParentBarcode());
            setParentDescription(value.getParentDescription());
            setParentContainerTypeId(value.getParentContainerTypeId());
            setParentContainerTypeName(value.getParentContainerTypeName());
            setParentContainerTypeDescription(value.getParentContainerTypeDescription());
            setParentContainerTypeIcon(value.getParentContainerTypeIcon());
            setContainerIsActive(value.getContainerIsActive());
            setTrialId(value.getTrialId());
            setTrialName(value.getTrialName());
            setTrialDescription(value.getTrialDescription());
            setProjectId(value.getProjectId());
            setProjectName(value.getProjectName());
            setProjectDescription(value.getProjectDescription());
            setContainerAttributes(value.getContainerAttributes());
            setSubContainerCount(value.getSubContainerCount());
            setCreatedOn(value.getCreatedOn());
        }
    }
    // @formatter:on
}
