/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.enums;


import org.jooq.*;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum AttributesDatatype implements EnumType {

    numeric("numeric"),

    text("text"),

    categorical("categorical"),

    date("date");

    private final String literal;

    private AttributesDatatype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "attributes_datatype";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static AttributesDatatype lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AttributesDatatype.class, literal);
    }
    // @formatter:on
}
