/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UsersUserType implements EnumType {

    admin("admin"),

    regular("regular"),

    reference("reference"),

    inactive("inactive");

    private final String literal;

    private UsersUserType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "users_user_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static UsersUserType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UsersUserType.class, literal);
    }
    // @formatter:on
}
