/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ViewTableUsersUserType implements EnumType {

    active("active"),

    reference("reference");

    private final String literal;

    private ViewTableUsersUserType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "view_table_users_user_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static ViewTableUsersUserType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ViewTableUsersUserType.class, literal);
    }
    // @formatter:on
}
