/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables;


import java.sql.Timestamp;
import java.util.Collection;

import jhi.seedstore.database.codegen.StashDb;
import jhi.seedstore.database.codegen.tables.records.ViewTableTransfersRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTransfers extends TableImpl<ViewTableTransfersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stash_db.view_table_transfers</code>
     */
    public static final ViewTableTransfers VIEW_TABLE_TRANSFERS = new ViewTableTransfers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewTableTransfersRecord> getRecordType() {
        return ViewTableTransfersRecord.class;
    }

    /**
     * The column <code>stash_db.view_table_transfers.transfer_event_id</code>.
     */
    public final TableField<ViewTableTransfersRecord, Integer> TRANSFER_EVENT_ID = createField(DSL.name("transfer_event_id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.container_id</code>.
     */
    public final TableField<ViewTableTransfersRecord, Integer> CONTAINER_ID = createField(DSL.name("container_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.container_barcode</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> CONTAINER_BARCODE = createField(DSL.name("container_barcode"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column
     * <code>stash_db.view_table_transfers.container_description</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> CONTAINER_DESCRIPTION = createField(DSL.name("container_description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.source_id</code>.
     */
    public final TableField<ViewTableTransfersRecord, Integer> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.source_barcode</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> SOURCE_BARCODE = createField(DSL.name("source_barcode"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.source_description</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> SOURCE_DESCRIPTION = createField(DSL.name("source_description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.target_id</code>.
     */
    public final TableField<ViewTableTransfersRecord, Integer> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.target_barcode</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> TARGET_BARCODE = createField(DSL.name("target_barcode"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.target_description</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> TARGET_DESCRIPTION = createField(DSL.name("target_description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.user_id</code>.
     */
    public final TableField<ViewTableTransfersRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.user_name</code>.
     */
    public final TableField<ViewTableTransfersRecord, String> USER_NAME = createField(DSL.name("user_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.created_on</code>.
     */
    public final TableField<ViewTableTransfersRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>stash_db.view_table_transfers.updated_on</code>.
     */
    public final TableField<ViewTableTransfersRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMP)), this, "");

    private ViewTableTransfers(Name alias, Table<ViewTableTransfersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ViewTableTransfers(Name alias, Table<ViewTableTransfersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `view_table_transfers` as select `stash`.`transfer_logs`.`transfer_event_id` AS `transfer_event_id`,`c`.`id` AS `container_id`,`c`.`barcode` AS `container_barcode`,`c`.`description` AS `container_description`,`s`.`id` AS `source_id`,`s`.`barcode` AS `source_barcode`,`s`.`description` AS `source_description`,`t`.`id` AS `target_id`,`t`.`barcode` AS `target_barcode`,`t`.`description` AS `target_description`,`stash`.`users`.`id` AS `user_id`,`stash`.`users`.`name` AS `user_name`,`stash`.`transfer_logs`.`created_on` AS `created_on`,`stash`.`transfer_logs`.`updated_on` AS `updated_on` from ((((`stash`.`transfer_logs` left join `stash`.`containers` `c` on((`c`.`id` = `stash`.`transfer_logs`.`container_id`))) left join `stash`.`containers` `s` on((`s`.`id` = `stash`.`transfer_logs`.`source_id`))) left join `stash`.`containers` `t` on((`t`.`id` = `stash`.`transfer_logs`.`target_id`))) left join `stash`.`users` on((`stash`.`transfer_logs`.`user_id` = `stash`.`users`.`id`)))"), where);
    }

    /**
     * Create an aliased <code>stash_db.view_table_transfers</code> table
     * reference
     */
    public ViewTableTransfers(String alias) {
        this(DSL.name(alias), VIEW_TABLE_TRANSFERS);
    }

    /**
     * Create an aliased <code>stash_db.view_table_transfers</code> table
     * reference
     */
    public ViewTableTransfers(Name alias) {
        this(alias, VIEW_TABLE_TRANSFERS);
    }

    /**
     * Create a <code>stash_db.view_table_transfers</code> table reference
     */
    public ViewTableTransfers() {
        this(DSL.name("view_table_transfers"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : StashDb.STASH_DB;
    }

    @Override
    public ViewTableTransfers as(String alias) {
        return new ViewTableTransfers(DSL.name(alias), this);
    }

    @Override
    public ViewTableTransfers as(Name alias) {
        return new ViewTableTransfers(alias, this);
    }

    @Override
    public ViewTableTransfers as(Table<?> alias) {
        return new ViewTableTransfers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableTransfers rename(String name) {
        return new ViewTableTransfers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableTransfers rename(Name name) {
        return new ViewTableTransfers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableTransfers rename(Table<?> name) {
        return new ViewTableTransfers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableTransfers where(Condition condition) {
        return new ViewTableTransfers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableTransfers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableTransfers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableTransfers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableTransfers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableTransfers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableTransfers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableTransfers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableTransfers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableTransfers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
    // @formatter:on
}
