/*
 * This file is generated by jOOQ.
 */
package jhi.seedstore.database.codegen.tables;


import java.sql.Timestamp;
import java.util.Collection;
import java.util.Map;

import jhi.seedstore.database.binding.UserStatsBinding;
import jhi.seedstore.database.codegen.StashDb;
import jhi.seedstore.database.codegen.enums.ViewTableUsersUserType;
import jhi.seedstore.database.codegen.tables.records.ViewTableUsersRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableUsers extends TableImpl<ViewTableUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stash_db.view_table_users</code>
     */
    public static final ViewTableUsers VIEW_TABLE_USERS = new ViewTableUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewTableUsersRecord> getRecordType() {
        return ViewTableUsersRecord.class;
    }

    /**
     * The column <code>stash_db.view_table_users.id</code>.
     */
    public final TableField<ViewTableUsersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stash_db.view_table_users.name</code>.
     */
    public final TableField<ViewTableUsersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stash_db.view_table_users.email_address</code>.
     */
    public final TableField<ViewTableUsersRecord, String> EMAIL_ADDRESS = createField(DSL.name("email_address"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stash_db.view_table_users.user_type</code>.
     */
    public final TableField<ViewTableUsersRecord, ViewTableUsersUserType> USER_TYPE = createField(DSL.name("user_type"), SQLDataType.VARCHAR(9).nullable(false).defaultValue(DSL.inline("reference", SQLDataType.VARCHAR)).asEnumDataType(ViewTableUsersUserType.class), this, "");

    /**
     * The column <code>stash_db.view_table_users.last_login</code>.
     */
    public final TableField<ViewTableUsersRecord, Timestamp> LAST_LOGIN = createField(DSL.name("last_login"), SQLDataType.TIMESTAMP(0), this, "");

    /**
     * The column <code>stash_db.view_table_users.created_on</code>.
     */
    public final TableField<ViewTableUsersRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>stash_db.view_table_users.stats</code>.
     */
    public final TableField<ViewTableUsersRecord, Map<String,Integer>> STATS = createField(DSL.name("stats"), SQLDataType.JSON, this, "", new UserStatsBinding());

    private ViewTableUsers(Name alias, Table<ViewTableUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ViewTableUsers(Name alias, Table<ViewTableUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `view_table_users` as select `stash`.`users`.`id` AS `id`,`stash`.`users`.`name` AS `name`,`stash`.`users`.`email_address` AS `email_address`,`stash`.`users`.`user_type` AS `user_type`,`stash`.`users`.`last_login` AS `last_login`,`stash`.`users`.`created_on` AS `created_on`,json_objectagg(ifnull(`t`.`yearmonth`,'null'),`t`.`count`) AS `stats` from (`stash`.`users` left join (select `stash`.`transfer_logs`.`user_id` AS `user_id`,date_format(`stash`.`transfer_logs`.`created_on`,'%Y-%m') AS `yearmonth`,count(1) AS `count` from `stash`.`transfer_logs` where ((to_days(now()) - to_days(`stash`.`transfer_logs`.`created_on`)) <= 365) group by `stash`.`transfer_logs`.`user_id`,date_format(`stash`.`transfer_logs`.`created_on`,'%Y-%m')) `t` on((`t`.`user_id` = `stash`.`users`.`id`))) group by `stash`.`users`.`id`"), where);
    }

    /**
     * Create an aliased <code>stash_db.view_table_users</code> table reference
     */
    public ViewTableUsers(String alias) {
        this(DSL.name(alias), VIEW_TABLE_USERS);
    }

    /**
     * Create an aliased <code>stash_db.view_table_users</code> table reference
     */
    public ViewTableUsers(Name alias) {
        this(alias, VIEW_TABLE_USERS);
    }

    /**
     * Create a <code>stash_db.view_table_users</code> table reference
     */
    public ViewTableUsers() {
        this(DSL.name("view_table_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : StashDb.STASH_DB;
    }

    @Override
    public ViewTableUsers as(String alias) {
        return new ViewTableUsers(DSL.name(alias), this);
    }

    @Override
    public ViewTableUsers as(Name alias) {
        return new ViewTableUsers(alias, this);
    }

    @Override
    public ViewTableUsers as(Table<?> alias) {
        return new ViewTableUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableUsers rename(String name) {
        return new ViewTableUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableUsers rename(Name name) {
        return new ViewTableUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableUsers rename(Table<?> name) {
        return new ViewTableUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableUsers where(Condition condition) {
        return new ViewTableUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewTableUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewTableUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
    // @formatter:on
}
